using System;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
namespace TVLounge {
internal static class CecClient {
 internal sealed class Result {public int Exit;public string Output;}
 public static string Find(){foreach(string root in new[]{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86)})foreach(string folder in new[]{@"Pulse-Eight\USB-CEC Adapter",@"Pulse-Eight\USB-CEC Adapter\x64",@"libCEC"}){string path=Path.Combine(root,folder,"cec-client.exe");if(File.Exists(path))return path;}return "";}
 public static void Validate(Settings s){if(s.CecHdmiPort<1||s.CecHdmiPort>15||s.CecWakeDelay<0||s.CecWakeDelay>30)throw new InvalidOperationException("Choose an HDMI input from 1–15 and a TV wake delay from 0–30 seconds.");if(!File.Exists(s.CecPath)||!string.Equals(Path.GetFileName(s.CecPath),"cec-client.exe",StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Select cec-client.exe from your installed libCEC software. A compatible CEC adapter and enabled TV CEC are required.");}
 internal static string Arguments(int port){return "-s -d 1 -t p -b 0 -p "+port;}
 internal static Result Run(string path,string arguments,string command){return RunTimed(path,arguments,command,25000);}
 internal static Result RunTimed(string path,string arguments,string command,int timeout){using(var process=new Process{StartInfo=new ProcessStartInfo(path,arguments){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Path.GetFullPath(path)),RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true}}){process.Start();var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();try{process.StandardInput.WriteLine(command);process.StandardInput.Close();if(!process.WaitForExit(timeout))throw new TimeoutException("CEC adapter did not respond. Close other CEC apps and check its USB connection.");Task.WaitAll(output,error);return new Result{Exit=process.ExitCode,Output=output.Result+"\n"+error.Result};}finally{if(!process.HasExited){process.Kill();process.WaitForExit();}}}}
 internal static void Wake(Settings s,Func<string,string,string,Result> run,Action<int> pause){string arguments=Arguments(s.CecHdmiPort);foreach(string command in new[]{"on 0","as"}){var result=run(s.CecPath,arguments,command);if(result.Exit!=0||new[]{"ERROR", "FAILED", "unable to open", "Cannot load"}.Any(v=>(result.Output??"").IndexOf(v,StringComparison.OrdinalIgnoreCase)>=0))throw new InvalidOperationException("TV control failed. Check the CEC adapter, libCEC installation and TV CEC setting. Your desktop setup has not been changed.");if(command=="on 0")pause(s.CecWakeDelay*1000);}}
 public static void Wake(Settings s){Validate(s);Wake(s,Run,Thread.Sleep);Storage.Log("CEC wake and HDMI "+s.CecHdmiPort+" active-source commands sent; TV response depends on CEC support.");}
 internal static int Fixture(string[] args){using(var input=new StreamReader(Console.OpenStandardInput()))using(var output=new StreamWriter(Console.OpenStandardOutput()))using(var error=new StreamWriter(Console.OpenStandardError())){string command=input.ReadLine();if(args.Contains("hang"))Thread.Sleep(5000);output.WriteLine(command);error.WriteLine("fixture stderr");return args.Contains("fail")?2:0;}}
 public static void Test(){var s=new Settings{CecHdmiPort=1,CecWakeDelay=3};if(s.CecEnabled)throw new Exception("CEC must default off");var calls=new System.Collections.Generic.List<string>();Wake(s,(path,args,command)=>{calls.Add(args+"|"+command);return new Result{Output="",Exit=0};},ms=>calls.Add("wait:"+ms));if(calls.Count!=3||!calls[0].EndsWith("|on 0")||calls[1]!="wait:3000"||!calls[2].EndsWith("|as")||!calls[0].Contains("-p 1"))throw new Exception("CEC wake/input ordering failed");bool failed=false;try{Wake(s,(path,args,command)=>new Result{Exit=1},ms=>{});}catch(InvalidOperationException){failed=true;}if(!failed)throw new Exception("CEC failure ignored");failed=false;try{Wake(s,(path,args,command)=>new Result{Output="ERROR: adapter unavailable"},ms=>{});}catch(InvalidOperationException){failed=true;}if(!failed)throw new Exception("CEC error ignored");var executable=typeof(Program).Assembly.Location;var child=RunTimed(executable,"--cec-fixture","on 0",5000);if(child.Exit!=0||!child.Output.Contains("on 0")||!child.Output.Contains("fixture stderr"))throw new Exception("CEC process streams failed");if(RunTimed(executable,"--cec-fixture fail","as",5000).Exit!=2)throw new Exception("CEC exit code lost");failed=false;try{RunTimed(executable,"--cec-fixture hang","on 0",500);}catch(TimeoutException){failed=true;}if(!failed)throw new Exception("CEC timeout ignored");var profile=DisplayProfile.Capture("CEC",new Settings{CecEnabled=true,CecPath="example",CecHdmiPort=4,CecWakeDelay=7});var destination=new Settings();profile.Apply(destination);if(!destination.CecEnabled||destination.CecHdmiPort!=4||destination.CecWakeDelay!=7||destination.CecPath!="example")throw new Exception("CEC profile persistence failed");string old=Storage.Data;try{Storage.Data=Path.Combine(old,"cec-engine-test");var fake=new FakeDevices();var engine=new Engine(fake);engine.Activate(new Settings{MonitorId="tv",CecEnabled=true,TimeoutSeconds=3});if(fake.Events[0]!="cec-wake"||!engine.Active)throw new Exception("TV must wake before display changes");engine.Restore(3);}finally{Storage.Data=old;}File.WriteAllText(Storage.PathOf("cec-test.txt"),"PASS: disabled default, wake/delay/input ordering, command failures, real subprocess input/output/exit handling and timeout cleanup, profile persistence, TV activation integration. No CEC hardware commands sent during tests.");}
}
}
