using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
namespace TVLounge {
public partial class MainForm {
 ModernSwitch controllerEnabled=new ModernSwitch(),awakeEnabled=new ModernSwitch(),updateChecks=new ModernSwitch(),automaticUpdates=new ModernSwitch();
 DarkCombo controllerChord=new DarkCombo(),profileList=new DarkCombo();NumberStepper controllerSeconds=new NumberStepper();TextBox profileName=new TextBox();
 Card controllerOptions=new Card(),awakeOptions=new Card(),profilesCard=new Card(),updatesCard=new Card(),supportCard=new Card();
 Label controllerInfo=Theme.Label("Connect an Xbox-compatible controller to use this shortcut.",9,false,Theme.Muted),awakeInfo=Theme.Label("Inactive in desktop mode. Your preference is saved.",9,false,Theme.Muted),updateInfo=Theme.Label("Check for a newer version on GitHub.",9,false,Theme.Muted),profileInfo=Theme.Label("Profiles save display, audio, gaming mode, and other-monitor behavior.",9,false,Theme.Muted);
 ModernButton checkUpdate=new ModernButton{Text="Check for updates"},installUpdate=new ModernButton{Text="Install update",Primary=true};
 ControllerInput controllers=new ControllerInput();AwakeGuard awake=new AwakeGuard();System.Windows.Forms.Timer controllerTimer=new System.Windows.Forms.Timer{Interval=100},updateTimer=new System.Windows.Forms.Timer{Interval=60000};
 List<DisplayProfile> profiles=new List<DisplayProfile>();UpdateRelease availableUpdate;UpdateHistory updateHistory=new UpdateHistory();bool checkingUpdate,installingUpdate,controllerTick;
 void AddFeatures(){
  Theme.Place(content,controllerOptions,32,504,808,176);Theme.Place(controllerOptions,Theme.Label("Controller shortcut",12,true,Theme.Text),24,16,650,28);
  Theme.Place(controllerOptions,controllerEnabled,738,18,46,28);controllerEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;controllerEnabled.Checked=settings.ControllerShortcut;controllerEnabled.AccessibleName="Enable controller TV mode shortcut";
  Theme.Place(controllerOptions,Theme.Label("Hold to enter TV mode. Release, then hold again to return to desktop.",9,false,Theme.Muted),24,48,710,25);
  foreach(var item in new[]{new Choice("816","View + Menu + LB + RB"),new Choice("48","View + Menu"),new Choice("192","L3 + R3"),new Choice("784","Menu + LB + RB")})controllerChord.Items.Add(item);
  controllerChord.SelectedItem=controllerChord.Items.Cast<Choice>().FirstOrDefault(c=>c.Id==settings.ControllerMask.ToString())??controllerChord.Items[0];Theme.Place(controllerOptions,controllerChord,24,84,480,38);controllerChord.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;
  controllerSeconds.Minimum=1;controllerSeconds.Maximum=5;controllerSeconds.Value=Math.Max(1,Math.Min(5,settings.ControllerHoldSeconds));Theme.Place(controllerOptions,controllerSeconds,550,84,110,38);controllerSeconds.Anchor=AnchorStyles.Right|AnchorStyles.Top;var holdLabel=Theme.Label("seconds",9,false,Theme.Muted);Theme.Place(controllerOptions,holdLabel,673,92,100,25);holdLabel.Anchor=AnchorStyles.Top|AnchorStyles.Right;
  Theme.Place(controllerOptions,controllerInfo,24,138,740,25);controllerInfo.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top;
  Theme.Place(content,awakeOptions,32,692,808,94);Theme.Place(awakeOptions,Theme.Label("Keep PC and TV awake in TV mode",11,true,Theme.Text),24,16,680,26);Theme.Place(awakeOptions,awakeEnabled,738,20,46,28);awakeEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;awakeEnabled.Checked=settings.KeepAwake;awakeEnabled.AccessibleName="Keep PC awake only in TV mode";Theme.Place(awakeOptions,awakeInfo,24,52,720,28);
  Theme.Place(content,profilesCard,32,8,808,290);Theme.Place(profilesCard,Theme.Label("Your saved setups",12,true,Theme.Text),24,16,700,28);Theme.Place(profilesCard,profileInfo,24,51,740,42);profileInfo.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top;
  Theme.Place(profilesCard,profileList,24,102,760,38);profileList.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top;profileName.BackColor=Theme.Input;profileName.ForeColor=Theme.Text;profileName.BorderStyle=BorderStyle.FixedSingle;profileName.MaxLength=64;Theme.Place(profilesCard,Theme.Label("PROFILE NAME",8,true,Theme.Muted),24,151,650,20);Theme.Place(profilesCard,profileName,24,177,760,34);profileName.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top;
  var useProfile=new ModernButton{Text="Use profile",Primary=true};Theme.Place(profilesCard,useProfile,24,244,160,40);var saveProfile=new ModernButton{Text="Save current setup"};Theme.Place(profilesCard,saveProfile,196,244,195,40);var deleteProfile=new ModernButton{Text="Delete profile"};Theme.Place(profilesCard,deleteProfile,403,244,165,40);
  try{profiles=ProfileStore.Load();}catch(Exception e){Storage.Log(e.ToString());profileInfo.Text="Saved profiles could not be read. Your current settings are unchanged.";}ReloadProfiles();profileList.SelectedIndexChanged+=delegate{if(profileList.SelectedItem is DisplayProfile)profileName.Text=((DisplayProfile)profileList.SelectedItem).Name;};
  useProfile.Click+=delegate{try{if(busy||engine.Active)throw new InvalidOperationException("Return to desktop before changing profiles.");var profile=profileList.SelectedItem as DisplayProfile;if(profile==null)throw new InvalidOperationException("Choose a saved profile.");var next=Clone(settings);profile.Apply(next);SetDeviceSelections(next);Save();status.Text="Profile loaded: "+profile.Name;}catch(Exception e){ShowError(e);}};
  saveProfile.Click+=delegate{try{if(engine.Active)throw new InvalidOperationException("Return to desktop before saving a profile.");Save();var next=new List<DisplayProfile>(profiles);ProfileStore.Put(next,DisplayProfile.Capture(profileName.Text,settings));Storage.Save("profiles.json",next);profiles=next;ReloadProfiles();status.Text="Display profile saved.";}catch(Exception e){ShowError(e);}};
  deleteProfile.Click+=delegate{try{var profile=profileList.SelectedItem as DisplayProfile;if(profile==null)return;var next=profiles.Where(p=>p!=profile).ToList();Storage.Save("profiles.json",next);profiles=next;ReloadProfiles();status.Text="Profile removed. Current settings are unchanged.";}catch(Exception e){ShowError(e);}};
  Theme.Place(content,updatesCard,32,8,808,250);Theme.Place(updatesCard,Theme.Label("SteamCouch updates",12,true,Theme.Text),24,16,700,28);Theme.Place(updatesCard,Theme.Label("Check for updates automatically",10,true,Theme.Text),24,57,650,26);Theme.Place(updatesCard,updateChecks,738,55,46,28);updateChecks.Anchor=AnchorStyles.Top|AnchorStyles.Right;updateChecks.Checked=settings.CheckUpdates;
  Theme.Place(updatesCard,Theme.Label("Install automatically while idle",10,true,Theme.Text),24,96,650,26);Theme.Place(updatesCard,automaticUpdates,738,94,46,28);automaticUpdates.Anchor=AnchorStyles.Top|AnchorStyles.Right;automaticUpdates.Checked=settings.AutoUpdate;
  Theme.Place(updatesCard,Theme.Label("Only while in desktop mode and the app is in the tray. Settings are preserved.",9,false,Theme.Muted),24,129,740,25);Theme.Place(updatesCard,updateInfo,24,165,740,28);updateInfo.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;Theme.Place(updatesCard,checkUpdate,24,202,190,36);Theme.Place(updatesCard,installUpdate,226,202,170,36);installUpdate.Enabled=false;
  var changes=new ModernButton{Text="What's new"};Theme.Place(updatesCard,changes,408,202,150,36);changes.Click+=delegate{if(availableUpdate!=null)System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("https://github.com/AymanFE/SteamCouch/releases/tag/v"+availableUpdate.Version){UseShellExecute=true});};
  checkUpdate.Click+=async delegate{await CheckForUpdates(true);};installUpdate.Click+=async delegate{await InstallAvailableUpdate();};
  Theme.Place(content,supportCard,32,276,808,220);Theme.Place(supportCard,Theme.Label("Set up and troubleshoot",12,true,Theme.Text),24,16,700,28);Theme.Place(supportCard,Theme.Label("The setup wizard guides you through TV, audio, and gaming mode choices.",9,false,Theme.Muted),24,52,740,28);var wizard=new ModernButton{Text="Run setup wizard",Primary=true};Theme.Place(supportCard,wizard,24,91,190,38);wizard.Click+=async delegate{await RunWizard();};Theme.Place(supportCard,Theme.Label("Check your selected devices and export a report you can review and share.",9,false,Theme.Muted),24,147,740,25);var diagnose=new ModernButton{Text="Troubleshoot"};Theme.Place(supportCard,diagnose,24,179,190,36);diagnose.Click+=async delegate{await Troubleshoot();};
  foreach(var card in new[]{controllerOptions,awakeOptions,profilesCard,updatesCard,supportCard})CaptureLayout(card);
  controllerTimer.Tick+=async delegate{if(controllerTick||uiTest)return;controllerTick=true;try{bool fire=controllers.Poll(settings.ControllerShortcut,settings.ControllerMask,settings.ControllerHoldSeconds,busy||installingUpdate||OwnedForms.Length>0);controllerInfo.Text=controllers.Connected+" controller(s). "+((settings.ControllerMask&0x400)!=0?"Xbox button can also open Steam menus; use a fallback if needed.":"Save settings to apply shortcut changes.");if(!fire)PollQuickMenu();if(fire)await Toggle();else await PollActions();}catch(Exception e){controllers.Reset();Storage.Log(e.ToString());}finally{controllerTick=false;}};
  updateTimer.Tick+=async delegate{if(busy||installingUpdate||OwnedForms.Length>0)return;if(settings.CheckUpdates&&DateTime.UtcNow-updateHistory.LastCheckUtc>TimeSpan.FromDays(1))await CheckForUpdates(false);if(settings.AutoUpdate&&availableUpdate!=null&&BackgroundUpdateAllowed())await InstallAvailableUpdate();};
 }
 static Settings Clone(Settings value){var json=new JavaScriptSerializer();return json.Deserialize<Settings>(json.Serialize(value));}
 void ReloadProfiles(){profileList.Items.Clear();foreach(var profile in profiles)profileList.Items.Add(profile);if(profileList.Items.Count>0)profileList.SelectedItem=profileList.Items[0];}
 void SetDeviceSelections(Settings next){
  var monitor=monitors.Items.Cast<Choice>().FirstOrDefault(c=>c.Id==next.MonitorId);if(monitor==null){monitor=new Choice(next.MonitorId,"Saved display (currently unavailable)");monitors.Items.Add(monitor);}monitors.SelectedItem=monitor;
  var output=audio.Items.Cast<Choice>().FirstOrDefault(c=>c.Id==next.AudioId);if(output==null){output=new Choice(next.AudioId,"Saved audio (currently unavailable)");audio.Items.Add(output);}audio.SelectedItem=output;launcher.SelectedItem=launcher.Items.Cast<Choice>().First(c=>c.Id==next.Launcher);steamPath.Text=next.SteamPath;SetOtherMonitorMode(next);steam.Checked=next.LaunchSteam;SetVideoPreferences(next);SetCec(next);SetGoogleTv(next);playnitePath.Text=next.PlaynitePath;
 }
 void SaveFeatureSettings(Settings next){next.ControllerShortcut=controllerEnabled.Checked;next.ControllerMask=int.Parse(((Choice)controllerChord.SelectedItem).Id);next.ControllerHoldSeconds=(int)controllerSeconds.Value;next.KeepAwake=awakeEnabled.Checked;next.CheckUpdates=updateChecks.Checked;next.AutoUpdate=automaticUpdates.Checked;next.SetupCompleted=settings.SetupCompleted;SaveQuickMenu(next);SaveOptional(next);SaveCec(next);SaveGoogleTv(next);controllers.Reset();}
 void LayoutFeatures(int width){
  var cards=new[]{controllerOptions,awakeOptions,profilesCard,updatesCard,supportCard};int[] pages={2,2,3,4,4},ys={504,692,8,8,276},heights={176,94,308,250,220};
  for(int i=0;i<cards.Length;i++){cards[i].SetBounds(Theme.Px(this,32),Theme.Px(this,ys[i]),width-Theme.Px(this,64),Theme.Px(this,heights[i]));cards[i].Visible=currentPage==pages[i];PlaceLogicalChildren(cards[i]);}
  if(currentPage==2)content.Height=awakeOptions.Bottom+Theme.Px(this,8);if(currentPage==3)content.Height=profilesCard.Bottom+Theme.Px(this,8);if(currentPage==4)content.Height=supportCard.Bottom+Theme.Px(this,8);
 }
 void UpdateFeatureMode(){if(awakeInfo==null||awakeEnabled==null)return;awakeInfo.Text=engine.Active?(settings.KeepAwake?"Active during this TV session. Released automatically on return to desktop.":"Off for this TV session. Enable and save to prevent idle sleep."):"Inactive in desktop mode. Your preference is saved.";if(!uiTest)try{awake.Update(engine.Active,settings.KeepAwake);}catch(Exception e){Storage.Log(e.ToString());awakeInfo.Text=e.Message;}installUpdate.Enabled=availableUpdate!=null&&!engine.Active&&!busy&&!installingUpdate;}
 async Task StartFeatures(){
  controllerTimer.Start();updateTimer.Start();couchTimer.Start();try{if(File.Exists(Storage.PathOf("update-history.json")))updateHistory=Storage.Read<UpdateHistory>("update-history.json");}catch(Exception e){Storage.Log(e.ToString());}
  if(!settings.SetupCompleted&&string.IsNullOrWhiteSpace(settings.MonitorId)&&!engine.Active)await RunWizard();
  if(settings.CheckUpdates&&DateTime.UtcNow-updateHistory.LastCheckUtc>TimeSpan.FromDays(1))await CheckForUpdates(false);
 }
 void DisposeFeatures(){couchTimer.Stop();couchTimer.Dispose();if(quickMenu!=null&&!quickMenu.IsDisposed)quickMenu.Close();controllerTimer.Stop();updateTimer.Stop();controllerTimer.Dispose();updateTimer.Dispose();awake.Dispose();}
 async Task CheckForUpdates(bool manual){
  if(checkingUpdate||installingUpdate)return;checkingUpdate=true;checkUpdate.Enabled=false;updateInfo.Text="Checking GitHub...";
  try{availableUpdate=await Task.Run(()=>UpdateService.Check());updateHistory.LastCheckUtc=DateTime.UtcNow;Storage.Save("update-history.json",updateHistory);updateInfo.Text=availableUpdate==null?"You're up to date. Installed version: "+UpdateService.Current:"Version "+availableUpdate.Version+" is available. Your settings will be kept.";if(availableUpdate!=null&&updateHistory.NotifiedVersion!=availableUpdate.Version){updateHistory.NotifiedVersion=availableUpdate.Version;Storage.Save("update-history.json",updateHistory);if(!uiTest)tray.ShowBalloonTip(5000,"SteamCouch update available","Version "+availableUpdate.Version+" — open Help & updates to install.",ToolTipIcon.Info);}}
  catch(Exception e){updateHistory.LastCheckUtc=DateTime.UtcNow;try{Storage.Save("update-history.json",updateHistory);}catch{}updateInfo.Text="Couldn't check right now. Try again later.";Storage.Log(e.ToString());if(manual)ShowError(e);}finally{checkingUpdate=false;checkUpdate.Enabled=true;UpdateFeatureMode();}
 }
 [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)] struct LastInput {public uint Size,Time;}
 [System.Runtime.InteropServices.DllImport("user32.dll")] static extern bool GetLastInputInfo(ref LastInput input);
 bool BackgroundUpdateAllowed(){var input=new LastInput{Size=8};return !engine.Active&&!Visible&&!busy&&OwnedForms.Length==0&&!SteamClient.IsBigPictureOpen()&&!PlayniteClient.Running&&controllers.Idle&&GetLastInputInfo(ref input)&&unchecked((uint)Environment.TickCount-input.Time)>=60000;}
 async Task InstallAvailableUpdate(){
  if(availableUpdate==null||busy||installingUpdate)return;bool background=!Visible;if(background&&!BackgroundUpdateAllowed())return;if(engine.Active||SteamClient.IsBigPictureOpen()){ShowError(new InvalidOperationException("Return to desktop and close Big Picture before installing an update."));return;}installingUpdate=true;busy=true;controllers.Reset();installUpdate.Enabled=false;checkUpdate.Enabled=false;save.Enabled=false;toggle.Enabled=false;updateInfo.Text="Downloading and checking the update...";
  try{string files=await Task.Run(()=>UpdateService.Download(availableUpdate));if(engine.Active)throw new InvalidOperationException("Return to desktop before updating.");UpdateService.Install(files,background);quitting=true;Close();}
  catch(Exception e){installingUpdate=false;busy=false;updateInfo.Text="Update wasn't installed. Your current version is unchanged.";save.Enabled=true;toggle.Enabled=true;checkUpdate.Enabled=true;UpdateFeatureMode();ShowError(e);}
 }
 async Task RunWizard(){
  if(busy||installingUpdate)return;if(engine.Active){ShowError(new InvalidOperationException("Return to desktop before running setup."));return;}controllers.Reset();
  try{var displays=await Task.Run(()=>devices.Monitors());var outputs=await Task.Run(()=>devices.Audio());using(var wizard=new SetupWizard(Clone(settings),displays,outputs,engine)){wizard.Icon=Icon;if(wizard.ShowDialog(this)==DialogResult.OK){SetDeviceSelections(wizard.Result);settings.SetupCompleted=true;Save();status.Text="Setup complete. Your couch is ready.";}}UpdateMode();}
  catch(Exception e){ShowError(e);}finally{controllers.Reset();UpdateMode();}
 }
 async Task Troubleshoot(){
  if(busy||installingUpdate)return;try{
   string report=await Task.Run(()=>{var displays=devices.Monitors();var outputs=devices.Audio();var tv=displays.FirstOrDefault(d=>d.Get("Monitor ID")==settings.MonitorId);var audioDevice=outputs.FirstOrDefault(a=>a.Get("Item ID")==settings.AudioId);return "SteamCouch "+UpdateService.Current+"\r\nChecked: "+DateTime.Now.ToString("g")+"\r\n\r\n"+(engine.Active?"TV session / recovery point exists. Restore desktop before changing profiles.":"Desktop mode. No TV recovery point.")+"\r\n\r\nTV: "+(tv==null?"Not found — check power/cable and refresh devices.":tv.Get("Monitor Name")+" — "+(Engine.IsOn(tv)?"connected":"disconnected; SteamCouch will reconnect it"))+"\r\nAudio: "+(string.IsNullOrEmpty(settings.AudioId)?"Automatic TV audio":audioDevice==null?"Not found — wake the TV and refresh devices.":audioDevice.Get("Name")+" — "+audioDevice.Get("Device State"))+"\r\nGaming mode: "+settings.Launcher+"\r\nSteam program: "+(File.Exists(settings.SteamPath)?"Found":"Not found; select Steam.exe in Settings")+"\r\nXbox mode supported: "+XboxClient.Supported+"\r\nController shortcut: "+(settings.ControllerShortcut?"Enabled":"Disabled")+"; connected controllers: "+controllers.Connected+"\r\nKeep awake preference: "+settings.KeepAwake+"; active request: "+awake.Active+"\r\n\r\nIf audio is wrong, select the TV output explicitly. If Steam opens elsewhere, use Steam's Automatic/Primary display setting. For failed restores, reconnect the original displays and retry Restore desktop.\r\n\r\nThis report includes device names, but omits device IDs, account names, and local file paths.";});
   using(var dialog=new Form{Text="SteamCouch — Troubleshoot",BackColor=Theme.Background,ForeColor=Theme.Text,ClientSize=new Size(760,560),StartPosition=FormStartPosition.CenterParent,MinimizeBox=false,MaximizeBox=false,AutoScaleMode=AutoScaleMode.Dpi,AutoScaleDimensions=new SizeF(96,96)}){var text=new RichTextBox{Text=report,ReadOnly=true,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,Font=new Font("Segoe UI",10),Dock=DockStyle.Fill};dialog.Controls.Add(text);var footer=new Panel{Dock=DockStyle.Bottom,Height=64};var export=new ModernButton{Text="Save report",Primary=true};Theme.Place(footer,export,24,12,150,38);export.Click+=delegate{using(var picker=new SaveFileDialog{Filter="Text report|*.txt",FileName="SteamCouch-report.txt"})if(picker.ShowDialog(dialog)==DialogResult.OK)File.WriteAllText(picker.FileName,report);};dialog.Controls.Add(footer);dialog.Shown+=delegate{Theme.DarkTitle(dialog);};dialog.ShowDialog(this);}
  }catch(Exception e){ShowError(e);}
 }
 void CheckFeatureBindings(){
  string path=Storage.PathOf("settings.json"),original=File.ReadAllText(path);var before=Clone(settings);
  try{controllerEnabled.Checked=!before.ControllerShortcut;awakeEnabled.Checked=!before.KeepAwake;automaticUpdates.Checked=!before.AutoUpdate;updateChecks.Checked=!before.CheckUpdates;controllerChord.SelectedItem=controllerChord.Items[1];controllerSeconds.Value=3;quickMenuEnabled.Checked=!before.QuickMenu;menuChord.SelectedItem=menuChord.Items[1];hdrPreference.SelectedItem=hdrPreference.Items[1];vrrSession.Checked=!before.TvVrr;Save();var saved=Storage.Read<Settings>("settings.json");if(saved.ControllerShortcut==before.ControllerShortcut||saved.KeepAwake==before.KeepAwake||saved.AutoUpdate==before.AutoUpdate||saved.CheckUpdates==before.CheckUpdates||saved.ControllerMask!=48||saved.ControllerHoldSeconds!=3||saved.QuickMenu==before.QuickMenu||saved.MenuMask!=16416||saved.TvHdr!="On"||saved.TvVrr==before.TvVrr)throw new Exception("Feature controls did not persist.");}
  finally{File.WriteAllText(path,original);settings=before;controllerEnabled.Checked=before.ControllerShortcut;awakeEnabled.Checked=before.KeepAwake;automaticUpdates.Checked=before.AutoUpdate;updateChecks.Checked=before.CheckUpdates;controllerChord.SelectedItem=controllerChord.Items.Cast<Choice>().First(c=>c.Id==before.ControllerMask.ToString());controllerSeconds.Value=before.ControllerHoldSeconds;quickMenuEnabled.Checked=before.QuickMenu;menuChord.SelectedItem=menuChord.Items.Cast<Choice>().First(c=>c.Id==before.MenuMask.ToString());SetVideoPreferences(before);UpdateMode();}
 }
 void PreviewWizard(){using(var wizard=new SetupWizard(Clone(settings),devices.Monitors(),devices.Audio(),engine)){wizard.Icon=Icon;wizard.Show(this);for(int step=0;step<5;step++){wizard.PreviewStep(step);wizard.Refresh();using(var bitmap=new Bitmap(wizard.Width,wizard.Height)){wizard.DrawToBitmap(bitmap,new Rectangle(0,0,wizard.Width,wizard.Height));bitmap.Save(Storage.PathOf("wizard-"+step+".png"));}}wizard.Close();}using(var dialog=new GoogleTvDialog(Clone(settings))){dialog.Icon=Icon;dialog.Show(this);dialog.Refresh();using(var bitmap=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(bitmap,new Rectangle(0,0,dialog.Width,dialog.Height));bitmap.Save(Storage.PathOf("google-tv-wizard.png"));}dialog.Close();}using(var guide=new GoogleTvGuide()){guide.Icon=Icon;guide.Show(this);Application.DoEvents();guide.Refresh();using(var bitmap=new Bitmap(guide.Width,guide.Height)){guide.DrawToBitmap(bitmap,new Rectangle(0,0,guide.Width,guide.Height));bitmap.Save(Storage.PathOf("google-tv-guide.png"));}guide.Close();}}
}
}
