using System;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
using System.Threading.Tasks;
using System.Collections.Generic;
namespace TVLounge {
public partial class MainForm {
 Card performanceCard=new Card(),batteryCard=new Card(),returnGameCard=new Card();ModernSwitch performanceEnabled=new ModernSwitch(),batteryEnabled=new ModernSwitch(),batteryPopup=new ModernSwitch(),batterySound=new ModernSwitch(),batteryVibration=new ModernSwitch(),returnGameEnabled=new ModernSwitch(),returnGameShortcut=new ModernSwitch(),performanceShortcut=new ModernSwitch();DarkCombo performanceLevel=new DarkCombo(),performanceCorner=new DarkCombo(),performanceDisplay=new DarkCombo(),performanceChord=new DarkCombo(),returnGameChord=new DarkCombo();NumberStepper performanceScale=new NumberStepper(),performanceOpacity=new NumberStepper();ModernSwitch[] metricSwitches=new ModernSwitch[9];Label[] metricLabels=new Label[9];ModernButton fpsPermission,returnButton;Label batteryStatus=Theme.Label("Enable monitoring to see connected controllers.",9,false,Theme.Muted),performanceStatus=Theme.Label("FPS capture starts only when the display is enabled.",9,false,Theme.Muted);
 readonly System.Windows.Forms.Timer gamingToolsTimer=new System.Windows.Forms.Timer{Interval=250};readonly FrameTracker frameTracker=new FrameTracker();readonly ControllerBatteries batteries=new ControllerBatteries();readonly BatteryAlertPolicy batteryAlerts=new BatteryAlertPolicy();readonly HardwareTelemetry hardware=new HardwareTelemetry();readonly GameFocus gameFocus=new GameFocus();readonly ControllerInput performanceController=new ControllerInput(),returnGameController=new ControllerInput();PerformanceCapture capture;PerformanceHud performanceHud;TelemetrySnapshot hardwareValues=new TelemetrySnapshot();List<BatteryReading> batteryValues=new List<BatteryReading>();bool toolsTick,toolsDisposed;DateTime batteryRead,hardwareRead;string cachedSessionDisplay;EventHandler toolsDisplayChanged;
 void AddGamingTools(){performanceEnabled.AccessibleName="Enable performance display";batteryEnabled.AccessibleName="Enable controller battery monitoring";returnGameEnabled.AccessibleName="Enable Return to game";returnGameShortcut.AccessibleName="Enable Return to game controller shortcut";performanceShortcut.AccessibleName="Enable performance controller shortcut";performanceScale.AccessibleName="Performance display size in percent";performanceOpacity.AccessibleName="Performance display opacity in percent";
  Theme.Place(content,performanceCard,32,1578,808,566);Theme.Place(performanceCard,Theme.Label("Performance display",12,true,Theme.Text),24,16,690,28);Theme.Place(performanceCard,performanceEnabled,738,18,46,28);performanceEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;performanceEnabled.Checked=settings.PerformanceEnabled;
  Theme.Place(performanceCard,Theme.Label("Deck-inspired levels · desktop and TV · click-through · best with borderless games",9,false,Theme.Muted),24,52,740,27);
  foreach(var c in new[]{new Choice("0","0 · Off"),new Choice("1","1 · FPS"),new Choice("2","2 · FPS, frame time & battery"),new Choice("3","3 · Usage, temperature & power"),new Choice("4","4 · Detailed hardware view")})performanceLevel.Items.Add(c);SelectTool(performanceLevel,settings.PerformanceLevel.ToString());Theme.Place(performanceCard,performanceLevel,24,88,456,36);
  foreach(var c in new[]{new Choice("0","Top left"),new Choice("1","Top right"),new Choice("2","Bottom left"),new Choice("3","Bottom right")})performanceCorner.Items.Add(c);SelectTool(performanceCorner,settings.PerformanceCorner.ToString());Theme.Place(performanceCard,performanceCorner,494,88,290,36);
  performanceDisplay.Items.Add(new Choice("Auto","Follow the focused game / app"));performanceDisplay.Items.Add(new Choice("TV","TV mode display"));foreach(var screen in Screen.AllScreens)performanceDisplay.Items.Add(new Choice(screen.DeviceName,screen.DeviceName));if(!performanceDisplay.Items.Cast<Choice>().Any(c=>c.Id==settings.PerformanceDisplay))performanceDisplay.Items.Add(new Choice(settings.PerformanceDisplay,"Saved display (currently unavailable)"));SelectTool(performanceDisplay,settings.PerformanceDisplay);Theme.Place(performanceCard,performanceDisplay,24,136,760,36);performanceDisplay.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top;
  Theme.Place(performanceCard,Theme.Label("SIZE %",8,true,Theme.Muted),24,186,90,24);performanceScale.Minimum=75;performanceScale.Maximum=200;performanceScale.Value=Math.Max(75,Math.Min(200,settings.PerformanceScale));Theme.Place(performanceCard,performanceScale,118,182,134,36);Theme.Place(performanceCard,Theme.Label("OPACITY %",8,true,Theme.Muted),282,186,108,24);performanceOpacity.Minimum=30;performanceOpacity.Maximum=100;performanceOpacity.Value=Math.Max(30,Math.Min(100,settings.PerformanceOpacity));Theme.Place(performanceCard,performanceOpacity,398,182,134,36);
  string[] labels={"Frame-time graph","Controller battery","CPU usage","GPU usage","Temperatures","Power in watts","GPU clocks","RAM / VRAM","Per-core CPU"};for(int i=0;i<9;i++){int x=24+i%3*254,y=234+i/3*38;metricLabels[i]=Theme.Label(labels[i],9,false,Theme.Text);Theme.Place(performanceCard,metricLabels[i],x,y,185,26);metricSwitches[i]=new ModernSwitch{Checked=(settings.PerformanceMetrics&(1<<i))!=0};Theme.Place(performanceCard,metricSwitches[i],x+186,y,46,26);metricSwitches[i].AccessibleName=labels[i];}
  Theme.Place(performanceCard,Theme.Label("CPU temperature/power and unsupported GPU sensors show unavailable. Watts are component power.",9,false,Theme.Muted),24,358,750,32);
  Theme.Place(performanceCard,Theme.Label("Controller shortcut to cycle levels 0–4",10,true,Theme.Text),24,398,685,26);Theme.Place(performanceCard,performanceShortcut,738,397,46,28);performanceShortcut.Anchor=AnchorStyles.Top|AnchorStyles.Right;performanceShortcut.Checked=settings.PerformanceShortcut;ToolChords(performanceChord,settings.PerformanceMask);Theme.Place(performanceCard,performanceChord,24,435,456,36);var permission=fpsPermission=new ModernButton{Text="Enable FPS capture"};Theme.Place(performanceCard,permission,494,435,290,36);permission.Click+=async delegate{try{Save();if(!settings.PerformanceEnabled||settings.PerformanceLevel==0)throw new InvalidOperationException("Enable the performance display and choose level 1–4 first. Windows may ask permission for the capture helper only.");EnsureCapture();await capture.EnablePermission();performanceStatus.Text=capture.Status;}catch(Exception e){ShowError(e);}};Theme.Place(performanceCard,performanceStatus,24,486,752,58);performanceStatus.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;
  Theme.Place(content,batteryCard,32,2156,808,280);Theme.Place(batteryCard,Theme.Label("Controller battery monitoring",12,true,Theme.Text),24,16,690,28);Theme.Place(batteryCard,batteryEnabled,738,18,46,28);batteryEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;batteryEnabled.Checked=settings.BatteryMonitoring;Theme.Place(batteryCard,Theme.Label("Works while SteamCouch runs, at your desk or on the couch. Unknown readings stay unknown.",9,false,Theme.Muted),24,53,740,29);
  var switches=new[]{batteryPopup,batterySound,batteryVibration};bool[] values={settings.BatteryPopup,settings.BatterySound,settings.BatteryVibration};string[] names={"Low-battery notification","Notification sound","Brief controller vibration"};for(int i=0;i<3;i++){Theme.Place(batteryCard,Theme.Label(names[i],10,false,Theme.Text),24,94+i*37,650,26);Theme.Place(batteryCard,switches[i],738,93+i*37,46,28);switches[i].Anchor=AnchorStyles.Top|AnchorStyles.Right;switches[i].Checked=values[i];switches[i].AccessibleName=names[i];}Theme.Place(batteryCard,batteryStatus,24,211,744,54);batteryStatus.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;
  Theme.Place(content,returnGameCard,32,2448,808,190);Theme.Place(returnGameCard,Theme.Label("Return to game",12,true,Theme.Text),24,16,690,28);Theme.Place(returnGameCard,returnGameEnabled,738,18,46,28);returnGameEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;returnGameEnabled.Checked=settings.ReturnGameEnabled;Theme.Place(returnGameCard,Theme.Label("Refocus the last game, or an open launcher if the game has closed. Only when you ask.",9,false,Theme.Muted),24,52,746,28);Theme.Place(returnGameCard,Theme.Label("Enable controller shortcut",10,false,Theme.Text),24,87,680,26);Theme.Place(returnGameCard,returnGameShortcut,738,86,46,28);returnGameShortcut.Anchor=AnchorStyles.Top|AnchorStyles.Right;returnGameShortcut.Checked=settings.ReturnGameShortcut;ToolChords(returnGameChord,settings.ReturnGameMask);Theme.Place(returnGameCard,returnGameChord,24,128,456,36);var resume=returnButton=new ModernButton{Text="Return to game"};Theme.Place(returnGameCard,resume,494,128,290,36);resume.Click+=delegate{try{Save();ReturnToGame();}catch(Exception e){ShowError(e);}};
  toolsDisplayChanged=delegate{try{if(!toolsDisposed&&IsHandleCreated)BeginInvoke((Action)(()=>cachedSessionDisplay=null));}catch(InvalidOperationException){}};Microsoft.Win32.SystemEvents.DisplaySettingsChanged+=toolsDisplayChanged;foreach(var card in new[]{performanceCard,batteryCard,returnGameCard}){foreach(var label in card.Controls.OfType<Label>().Where(l=>l.Width>=600))label.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;CaptureLayout(card);}gamingToolsTimer.Tick+=async delegate{if(toolsTick||uiTest||toolsDisposed)return;toolsTick=true;try{await UpdateGamingTools();}catch(Exception e){Storage.Log("Gaming tools: "+e.Message);}finally{toolsTick=false;}};
  tray.ContextMenuStrip.Items.Insert(2,new ToolStripMenuItem("Return to game",null,delegate{ReturnToGame();}));tray.ContextMenuStrip.Items.Insert(3,new ToolStripMenuItem("Controller batteries",null,delegate{MessageBox.Show(this,BatteryDetails(),"Controller batteries",MessageBoxButtons.OK,MessageBoxIcon.Information);}));tray.ContextMenuStrip.Items.Insert(4,new ToolStripMenuItem("Cycle performance display",null,delegate{CyclePerformance();}));var displayToggle=new ToolStripMenuItem("Enable performance display",null,delegate{TogglePerformanceDisplay();});tray.ContextMenuStrip.Items.Insert(4,displayToggle);tray.ContextMenuStrip.Opening+=delegate{displayToggle.Text=settings.PerformanceEnabled?"Disable performance display":"Enable performance display";displayToggle.Enabled=!busy&&!installingUpdate;};
 }
 static void SelectTool(DarkCombo box,string id){box.SelectedItem=box.Items.Cast<Choice>().FirstOrDefault(c=>c.Id==id)??box.Items[0];}
 static void ToolChords(DarkCombo box,int mask){foreach(var c in new[]{new Choice("4128","View / Select + A"),new Choice("8224","View / Select + B"),new Choice("16416","View / Select + X"),new Choice("32800","View / Select + Y")})box.Items.Add(c);SelectTool(box,mask.ToString());}
 void LayoutGamingTools(int width){var cards=new[]{performanceCard,batteryCard,returnGameCard};int[] ys={1578,2156,2448},hs={566,280,190};for(int i=0;i<cards.Length;i++){cards[i].SetBounds(Theme.Px(this,32),Theme.Px(this,ys[i]),width-Theme.Px(this,64),Theme.Px(this,hs[i]));cards[i].Visible=currentPage==2;PlaceLogicalChildren(cards[i]);}int margin=Theme.Px(this,24),gap=Theme.Px(this,14),available=performanceCard.ClientSize.Width-2*margin,left=(int)((available-gap)*.6),right=available-gap-left;foreach(var combo in new[]{performanceLevel,performanceChord})combo.SetBounds(margin,combo.Top,left,combo.Height);performanceCorner.SetBounds(margin+left+gap,performanceCorner.Top,right,performanceCorner.Height);fpsPermission.SetBounds(margin+left+gap,fpsPermission.Top,right,fpsPermission.Height);returnGameChord.SetBounds(margin,returnGameChord.Top,left,returnGameChord.Height);returnButton.SetBounds(margin+left+gap,returnButton.Top,right,returnButton.Height);int column=available/3;for(int i=0;i<9;i++){int x=margin+i%3*column,y=Theme.Px(this,234+i/3*38),toggleWidth=Theme.Px(this,46);metricLabels[i].SetBounds(x,y,column-toggleWidth-Theme.Px(this,10),Theme.Px(this,26));metricSwitches[i].SetBounds(x+column-toggleWidth-Theme.Px(this,4),y,toggleWidth,Theme.Px(this,26));}if(currentPage==2)content.Height=returnGameCard.Bottom+Theme.Px(this,8);}
 void SaveGamingTools(Settings next){next.PerformanceEnabled=performanceEnabled.Checked;next.PerformanceLevel=int.Parse(((Choice)performanceLevel.SelectedItem).Id);next.PerformanceCorner=int.Parse(((Choice)performanceCorner.SelectedItem).Id);next.PerformanceDisplay=((Choice)performanceDisplay.SelectedItem).Id;next.PerformanceScale=(int)performanceScale.Value;next.PerformanceOpacity=(int)performanceOpacity.Value;next.PerformanceMetrics=0;for(int i=0;i<9;i++)if(metricSwitches[i].Checked)next.PerformanceMetrics|=1<<i;next.PerformanceShortcut=performanceShortcut.Checked;next.PerformanceMask=int.Parse(((Choice)performanceChord.SelectedItem).Id);next.BatteryMonitoring=batteryEnabled.Checked;next.BatteryPopup=batteryPopup.Checked;next.BatterySound=batterySound.Checked;next.BatteryVibration=batteryVibration.Checked;next.ReturnGameEnabled=returnGameEnabled.Checked;next.ReturnGameShortcut=returnGameShortcut.Checked;next.ReturnGameMask=int.Parse(((Choice)returnGameChord.SelectedItem).Id);OptionalPolicy.Validate(next);performanceController.Reset();returnGameController.Reset();}
 void PollGamingToolShortcuts(){bool blocked=busy||installingUpdate||OwnedForms.Length>0;if(returnGameController.PollMilliseconds(settings.ReturnGameEnabled&&settings.ReturnGameShortcut,settings.ReturnGameMask,500,blocked)){ReturnToGame();return;}if(performanceController.PollMilliseconds(settings.PerformanceEnabled&&settings.PerformanceShortcut,settings.PerformanceMask,500,blocked))CyclePerformance();}
 void TogglePerformanceDisplay(){try{if(busy||installingUpdate)return;var next=Clone(settings);next.PerformanceEnabled=!settings.PerformanceEnabled;if(next.PerformanceEnabled&&next.PerformanceLevel==0)next.PerformanceLevel=1;Storage.Save("settings.json",next);settings=next;performanceEnabled.Checked=next.PerformanceEnabled;SelectTool(performanceLevel,next.PerformanceLevel.ToString());performanceController.Reset();if(!next.PerformanceEnabled){if(performanceHud!=null){performanceHud.Close();performanceHud=null;}if(capture!=null){capture.Dispose();capture=null;}performanceStatus.Text="Performance display off. No frame capture running.";}status.Text=next.PerformanceEnabled?"Performance display enabled.":"Performance display disabled.";}catch(Exception e){ShowError(e);}}
 void CyclePerformance(){if(!settings.PerformanceEnabled){status.Text="Enable the performance display in Settings first.";return;}SetPerformanceLevel((settings.PerformanceLevel+1)%5);}
 void SetPerformanceLevel(int level){if(!settings.PerformanceEnabled)return;var next=Clone(settings);next.PerformanceLevel=Math.Max(0,Math.Min(4,level));Storage.Save("settings.json",next);settings=next;SelectTool(performanceLevel,next.PerformanceLevel.ToString());status.Text="Performance display: level "+next.PerformanceLevel;}
 void ReturnToGame(){if(!settings.ReturnGameEnabled){status.Text="Enable Return to game in Settings first.";return;}if(busy||installingUpdate)return;status.Text=gameFocus.Return(settings)?"Returned to game or launcher.":"No game or launcher could be focused. Launch a game or select its taskbar button.";}
 string BatteryDetails(){if(!settings.BatteryMonitoring)return "Battery monitoring is off. Enable it in Settings.";return batteryValues.Count>0?string.Join(Environment.NewLine,batteryValues.Select(r=>r.Name+": "+r.Value)):batteries.Error.Length>0?batteries.Error:"No controller connected.";}
 string BatterySummary(){return !settings.BatteryMonitoring?"Battery monitoring off":batteryValues.Count==0?"No controller connected":string.Join(" · ",batteryValues.Select((r,i)=>(batteryValues.Count>1?"P"+(i+1)+" ":"")+r.Value));}
 void EnsureCapture(){if(capture==null)capture=new PerformanceCapture(frameTracker);capture.Start();}
 async Task UpdateGamingTools(){if(settings.ReturnGameEnabled||settings.PerformanceEnabled)gameFocus.Observe();if(settings.BatteryMonitoring&&DateTime.UtcNow-batteryRead>TimeSpan.FromSeconds(4)){batteryRead=DateTime.UtcNow;batteryValues=batteries.Read();batteryStatus.Text=BatteryDetails();foreach(var r in batteryValues)if((settings.BatteryPopup||settings.BatterySound||settings.BatteryVibration)&&batteryAlerts.Check(r,DateTime.UtcNow)){if(settings.BatteryPopup)tray.ShowBalloonTip(7000,"Controller battery low",r.Name+": "+r.Value,ToolTipIcon.Warning);if(settings.BatterySound)System.Media.SystemSounds.Exclamation.Play();if(settings.BatteryVibration)batteries.Vibrate(r);}}if(!settings.BatteryMonitoring){batteries.Dispose();batteryValues.Clear();batteryStatus.Text="Monitoring off. Your notification preferences are saved.";}
  if(!settings.PerformanceEnabled||settings.PerformanceLevel==0||(settings.PerformanceDisplay=="TV"&&!engine.Active)){if(capture!=null){if(!settings.PerformanceEnabled){capture.Dispose();capture=null;}else capture.Pause();}if(performanceHud!=null){performanceHud.Close();performanceHud=null;}performanceStatus.Text=settings.PerformanceDisplay=="TV"&&!engine.Active?"TV display selected · inactive in desktop mode.":"Performance display off. No frame capture running.";cachedSessionDisplay=null;return;}EnsureCapture();frameTracker.Target(gameFocus.ObservedPid);if(settings.PerformanceLevel>=3&&DateTime.UtcNow-hardwareRead>TimeSpan.FromSeconds(1)){hardwareRead=DateTime.UtcNow;hardwareValues=await Task.Run(()=>hardware.Read());if(toolsDisposed)return;}string display=settings.PerformanceDisplay=="TV"?(cachedSessionDisplay??(cachedSessionDisplay=engine.SessionDisplay())):settings.PerformanceDisplay=="Auto"?gameFocus.ObservedDisplay:settings.PerformanceDisplay;if(string.IsNullOrEmpty(display))display=Screen.PrimaryScreen.DeviceName;if(performanceHud==null)performanceHud=new PerformanceHud();performanceHud.Frames=frameTracker.Snapshot();performanceHud.Hardware=hardwareValues;performanceHud.Battery=BatterySummary();performanceHud.CaptureStatus=capture.Status;performanceHud.AppName=gameFocus.ObservedName??"Game";performanceHud.Configure(settings,display);performanceStatus.Text=capture.Status;
 }
  void CheckGamingToolBindings(){string path=Storage.PathOf("settings.json"),original=System.IO.File.ReadAllText(path);var old=Clone(settings);try{performanceEnabled.Checked=true;SelectTool(performanceLevel,"4");SelectTool(performanceCorner,"2");performanceScale.Value=125;performanceOpacity.Value=75;metricSwitches[0].Checked=false;batteryEnabled.Checked=true;batteryPopup.Checked=false;batterySound.Checked=true;batteryVibration.Checked=true;returnGameEnabled.Checked=true;returnGameShortcut.Checked=true;SelectTool(returnGameChord,"4128");performanceShortcut.Checked=true;SelectTool(performanceChord,"16416");Save();var saved=Storage.Read<Settings>("settings.json");if(!saved.PerformanceEnabled||saved.PerformanceLevel!=4||saved.PerformanceCorner!=2||saved.PerformanceScale!=125||saved.PerformanceOpacity!=75||(saved.PerformanceMetrics&1)!=0||!saved.BatteryMonitoring||saved.BatteryPopup||!saved.BatterySound||!saved.BatteryVibration||!saved.ReturnGameEnabled||!saved.ReturnGameShortcut||!saved.PerformanceShortcut)throw new Exception("Gaming tools settings did not persist.");TogglePerformanceDisplay();if(settings.PerformanceEnabled||performanceEnabled.Checked||performanceHud!=null||capture!=null||Storage.Read<Settings>("settings.json").PerformanceEnabled)throw new Exception("Tray disable did not stop and persist the performance display.");TogglePerformanceDisplay();if(!settings.PerformanceEnabled||!performanceEnabled.Checked||!Storage.Read<Settings>("settings.json").PerformanceEnabled)throw new Exception("Tray enable did not persist.");}finally{System.IO.File.WriteAllText(path,original);settings=old;performanceEnabled.Checked=old.PerformanceEnabled;SelectTool(performanceLevel,old.PerformanceLevel.ToString());SelectTool(performanceCorner,old.PerformanceCorner.ToString());performanceScale.Value=old.PerformanceScale;performanceOpacity.Value=old.PerformanceOpacity;for(int i=0;i<9;i++)metricSwitches[i].Checked=(old.PerformanceMetrics&(1<<i))!=0;batteryEnabled.Checked=old.BatteryMonitoring;batteryPopup.Checked=old.BatteryPopup;batterySound.Checked=old.BatterySound;batteryVibration.Checked=old.BatteryVibration;returnGameEnabled.Checked=old.ReturnGameEnabled;returnGameShortcut.Checked=old.ReturnGameShortcut;SelectTool(returnGameChord,old.ReturnGameMask.ToString());performanceShortcut.Checked=old.PerformanceShortcut;SelectTool(performanceChord,old.PerformanceMask.ToString());}}
 void PreviewGamingTools(){SelectPage(2);foreach(var card in new[]{performanceCard,batteryCard,returnGameCard}){panel.ScrollControlIntoView(card);Refresh();using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,ClientRectangle);b.Save(Storage.PathOf(card==performanceCard?"performance-settings.png":card==batteryCard?"battery-settings.png":"return-game-settings.png"));}}panel.AutoScrollPosition=Point.Empty;}
 void DisposeGamingTools(){toolsDisposed=true;Microsoft.Win32.SystemEvents.DisplaySettingsChanged-=toolsDisplayChanged;gamingToolsTimer.Stop();gamingToolsTimer.Dispose();if(performanceHud!=null){performanceHud.Close();performanceHud=null;}if(capture!=null){capture.Dispose();capture=null;}batteries.Dispose();hardware.Dispose();}
}
}