using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Net;
using System.Net.Sockets;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
namespace TVLounge {
internal static class GoogleTv {
 internal sealed class Reply {public int Exit;public string Text;}
 static readonly object gate=new object();const int ServerPort=5039;
 public static string Adb {get{return Path.Combine(Storage.Root,@"tools\adb\adb.exe");}}
 public static string Endpoint(string host){host=(host??"").Trim();var parts=host.Split(':');IPAddress address;int port=5555;if(parts.Length<1||parts.Length>2||!IPAddress.TryParse(parts[0],out address)||address.AddressFamily!=AddressFamily.InterNetwork||address.Equals(IPAddress.Any)||address.Equals(IPAddress.Broadcast)||address.GetAddressBytes()[0]>=224||parts.Length==2&&(!int.TryParse(parts[1],out port)||port<1||port>65535))throw new InvalidOperationException("Enter your TV's IPv4 address, optionally followed by :port. Use the connection port shown on Wireless debugging, or 5555 for older network debugging.");return address+":"+port;}
 public static byte[] Magic(string mac){string value=Regex.Replace(mac??"","[:-]","");if(!Regex.IsMatch(value,"\\A[0-9A-Fa-f]{12}\\z"))throw new InvalidOperationException("Enter the TV network MAC address as six pairs, such as AA:BB:CC:DD:EE:FF, or leave it blank.");var bytes=Enumerable.Range(0,6).Select(i=>Convert.ToByte(value.Substring(i*2,2),16)).ToArray();var packet=new byte[102];for(int i=0;i<6;i++)packet[i]=255;for(int i=6;i<102;i++)packet[i]=bytes[(i-6)%6];return packet;}
 public static void Validate(Settings s){Endpoint(s.GoogleTvHost);if(s.GoogleTvHdmiPort<1||s.GoogleTvHdmiPort>4||s.GoogleTvWakeDelay<0||s.GoogleTvWakeDelay>30)throw new InvalidOperationException("Choose HDMI 1–4 and a wake delay from 0–30 seconds.");if(!string.IsNullOrWhiteSpace(s.GoogleTvMac))Magic(s.GoogleTvMac.Trim());if(!string.IsNullOrWhiteSpace(s.GoogleTvInputUri)&&!Regex.IsMatch(s.GoogleTvInputUri,"\\Acontent://android\\.media\\.tv/passthrough/[A-Za-z0-9%_./-]+\\z"))throw new InvalidOperationException("The optional input URI must be an Android TV passthrough content URI, without spaces or shell commands.");if(!File.Exists(Adb))throw new InvalidOperationException("Bundled Google TV software is missing. Extract the full SteamCouch package or reinstall.");}
 internal static Reply Run(string arguments,string input,int timeout){string home=Storage.PathOf("google-tv");Directory.CreateDirectory(home);var start=new ProcessStartInfo(Adb,"-P "+ServerPort+" "+arguments){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Adb),RedirectStandardOutput=true,RedirectStandardError=true,RedirectStandardInput=true};start.EnvironmentVariables["ANDROID_USER_HOME"]=home;using(var process=new Process{StartInfo=start}){process.Start();var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();try{if(input!=null)process.StandardInput.WriteLine(input);process.StandardInput.Close();if(!process.WaitForExit(timeout))throw new TimeoutException("TV connection timed out. Check its IP address, debugging setting, and network standby. If prompted, allow this PC on the TV.");if(!Task.WaitAll(new Task[]{output,error},3000))throw new TimeoutException("Google TV helper did not finish responding.");return new Reply{Exit=process.ExitCode,Text=output.Result+"\n"+error.Result};}finally{if(!process.HasExited){process.Kill();process.WaitForExit();}}}}
 static bool Failed(Reply reply){return reply.Exit!=0||Regex.IsMatch(reply.Text??"","(?im)(^error:|failed|cannot connect|unable to connect|connection refused|no route to host)");}
 internal static string Describe(string text){if((text??"").IndexOf("unauthorized",StringComparison.OrdinalIgnoreCase)>=0)return "Allow this PC on the TV's debugging prompt. For Wireless debugging, pair with its six-digit code first.";if((text??"").IndexOf("offline",StringComparison.OrdinalIgnoreCase)>=0)return "The TV connection is offline. Wake the TV and reconnect in TV & audio.";return "TV is unreachable. Check its address and connection port, enable USB/network debugging, and enable network standby or Screenless service for wake from standby.";}
 internal static void ConnectCore(Settings s,int seconds,Func<string,string,int,Reply> run,Action<int> pause){string endpoint=Endpoint(s.GoogleTvHost);var watch=Stopwatch.StartNew();string last="";do{var connected=run("connect "+endpoint,null,Math.Min(10000,Math.Max(1000,seconds*1000-(int)watch.ElapsedMilliseconds)));last=connected.Text;var state=run("-s "+endpoint+" get-state",null,5000);last=state.Text;if(state.Exit==0&&state.Text.Trim()=="device")return;if(seconds<=0)break;pause(1000);}while(watch.Elapsed.TotalSeconds<seconds);throw new InvalidOperationException(Describe(last));}
 public static void Connect(Settings s){Validate(s);lock(gate){ConnectCore(s,45,Run,Thread.Sleep);}}
 public static void Pair(Settings s,string pairingEndpoint,string code){Validate(s);pairingEndpoint=Endpoint(pairingEndpoint);if(pairingEndpoint.Split(':')[0]!=Endpoint(s.GoogleTvHost).Split(':')[0])throw new InvalidOperationException("Use the pairing address for the same TV as the connection address.");if(!Regex.IsMatch(code??"","\\A[0-9]{6}\\z"))throw new InvalidOperationException("Enter the six-digit pairing code shown on the TV.");lock(gate){var reply=Run("pair "+pairingEndpoint,code,45000);if(Failed(reply)||!reply.Text.Contains("Successfully paired"))throw new InvalidOperationException("Pairing failed. Open Pair using pairing code on the TV and enter its current pairing port and code. The pairing port differs from the connection port.");}}
 internal static bool HardwareUri(string value){return Regex.IsMatch(value??"",@"\Acontent://android\.media\.tv/passthrough/[A-Za-z0-9%_./-]+(?:%2[Ff]|/)HW[0-9]+\z");}
 internal static string InputCommand(Settings s){return string.IsNullOrWhiteSpace(s.GoogleTvInputUri)||HardwareUri(s.GoogleTvInputUri)?"input keyevent "+(242+s.GoogleTvHdmiPort):"am start -a android.intent.action.VIEW -d "+s.GoogleTvInputUri;}
 internal static string DiscoverInput(string dump,int port){
  var hardware=new HashSet<string>();
  foreach(Match info in Regex.Matches(dump??"",@"TvInputHardwareInfo\s*\{([^}]+)\}")){
   var id=Regex.Match(info.Groups[1].Value,@"\bid=(\d+)\b");var hdmi=Regex.Match(info.Groups[1].Value,@"\bhdmi_port=(\d+)\b");
   if(id.Success&&hdmi.Success&&hdmi.Groups[1].Value==port.ToString())hardware.Add(id.Groups[1].Value);
  }
  var section=Regex.Match(dump??"",@"(?ms)^\s*mHardwareInputIdMap:[^\r\n]*\r?\n(.*?)(?=^\s*m[A-Z]\w*:|\z)");
  var inputs=new HashSet<string>();
  foreach(Match row in Regex.Matches(section.Groups[1].Value,@"(?m)^\s*(\d+):\s*([A-Za-z0-9_.$/-]+)\s*$"))if(hardware.Contains(row.Groups[1].Value))inputs.Add(row.Groups[2].Value);
  return inputs.Count==1?"content://android.media.tv/passthrough/"+Uri.EscapeDataString(inputs.Single()):null;
 }
 internal static string ResolveInput(Settings s,Func<string,string,int,Reply> run){
  if(!string.IsNullOrWhiteSpace(s.GoogleTvInputUri)&&!HardwareUri(s.GoogleTvInputUri))return InputCommand(s);
  Reply reply=null;try{reply=run("-s "+Endpoint(s.GoogleTvHost)+" shell dumpsys tv_input",null,10000);}catch(TimeoutException){if(HardwareUri(s.GoogleTvInputUri))throw;}
  string uri=reply!=null&&!Failed(reply)?DiscoverInput(reply.Text,s.GoogleTvHdmiPort):null;
  if(uri!=null)return "am start -a android.intent.action.VIEW -d "+uri;
  if(HardwareUri(s.GoogleTvInputUri))throw new InvalidOperationException("Could not identify HDMI "+s.GoogleTvHdmiPort+" on the TV. Reconnect and try again; the old saved input will not override your selected port.");
  return InputCommand(s);
 }
 internal static void WakeCore(Settings s,Func<string,string,int,Reply> run,Action<int> pause,Action<byte[]> wol){if(!string.IsNullOrWhiteSpace(s.GoogleTvMac))wol(Magic(s.GoogleTvMac.Trim()));ConnectCore(s,Math.Max(3,Math.Min(30,s.TimeoutSeconds)),run,pause);string prefix="-s "+Endpoint(s.GoogleTvHost)+" shell ";var awake=run(prefix+"input keyevent 224",null,10000);if(Failed(awake))throw new InvalidOperationException("TV command failed. "+Describe(awake.Text));pause(Math.Max(1500,s.GoogleTvWakeDelay*1000));var selected=run(prefix+ResolveInput(s,run),null,10000);if(Failed(selected)||Regex.IsMatch(selected.Text??"",@"(?im)(Error:|Exception|unable to resolve Intent)"))throw new InvalidOperationException("TV input command failed. "+Describe(selected.Text));}
 public static void Wake(Settings s){Validate(s);lock(gate){WakeCore(s,Run,Thread.Sleep,packet=>{using(var client=new UdpClient()){client.EnableBroadcast=true;client.Send(packet,packet.Length,new IPEndPoint(IPAddress.Broadcast,9));}});}Storage.Log("Google TV wake and HDMI "+s.GoogleTvHdmiPort+" input commands sent; verify the TV honors them.");}
 internal static void StandbyCore(string host,Func<string,string,int,Reply> run){string endpoint=Endpoint(host);var reply=run("-s "+endpoint+" shell input keyevent 223",null,10000);if(Failed(reply))throw new InvalidOperationException("TV standby command failed. "+Describe(reply.Text));}
 public static void Standby(string host){Endpoint(host);if(!File.Exists(Adb))throw new InvalidOperationException("Bundled Google TV software is missing. Reinstall SteamCouch.");lock(gate){ConnectCore(new Settings{GoogleTvHost=host},3,Run,Thread.Sleep);StandbyCore(host,Run);}Storage.Log("Google TV standby command sent after desktop restoration.");}
 public static void Test(){var version=Run("version",null,5000);if(version.Exit!=0||!version.Text.Contains("37.0.1"))throw new Exception("Bundled ADB cannot load");Action<bool,string> check=(value,label)=>{if(!value)throw new Exception(label);};check(Endpoint("192.0.2.10")=="192.0.2.10:5555","Default TV port");check(Endpoint("192.0.2.10:37123").EndsWith(":37123"),"Wireless connection port");foreach(string invalid in new[]{"192.168.1.2;reboot","192.168.1.2:0","255.255.255.255","localhost","1.2.3.4:5555:5555"}){bool rejected=false;try{Endpoint(invalid);}catch(InvalidOperationException){rejected=true;}check(rejected,"Invalid TV address accepted");}var packet=Magic("01:02:03:04:05:06");check(packet.Length==102&&packet.Take(6).All(v=>v==255)&&packet[6]==1&&packet[101]==6,"Magic packet layout");var s=new Settings{GoogleTvHost="192.0.2.10",GoogleTvHdmiPort=1,GoogleTvMac="01:02:03:04:05:06"};check(!s.GoogleTvEnabled,"Network TV defaults off");var events=new List<string>();WakeCore(s,(args,input,timeout)=>{events.Add(args);return new Reply{Text=args.Contains("get-state")?"device":"",Exit=0};},ms=>events.Add("delay:"+ms),p=>events.Add("wol"));check(events[0]=="wol"&&events.IndexOf("-s 192.0.2.10:5555 shell input keyevent 224")<events.IndexOf("-s 192.0.2.10:5555 shell input keyevent 243"),"Wake precedes selected HDMI");check(Describe("unauthorized").StartsWith("Allow"),"Unauthorized message");bool failed=false;try{ConnectCore(s,0,(args,input,timeout)=>new Reply{Exit=1,Text="unauthorized"},ms=>{});}catch(InvalidOperationException){failed=true;}check(failed,"Unauthorized must stop activation");s.GoogleTvInputUri="content://android.media.tv/passthrough/com.tcl.tvinput%2F.Service%2FHW15";Validate(s);check(HardwareUri(s.GoogleTvInputUri),"Legacy hardware URI recognized");
 var dump="mHardwareList:\nTvInputHardwareInfo {id=45, type=9, hdmi_port=1}\nTvInputHardwareInfo {id=91, type=9, hdmi_port=2}\nmHardwareInputIdMap: deviceId -> inputId\n  45: com.tcl.tvinput/.Service/HW45\n  91: com.tcl.tvinput/.Service/HW91\nmHdmiInputIdMap: id -> inputId\n";
 check(DiscoverInput(dump,2)=="content://android.media.tv/passthrough/com.tcl.tvinput%2F.Service%2FHW91","Use reported HDMI mapping, not hardware ID arithmetic");
 check(DiscoverInput(dump,3)==null,"Missing HDMI does not select another port");
 s.GoogleTvHdmiPort=2;events.Clear();WakeCore(s,(args,input,timeout)=>{events.Add(args);return new Reply{Text=args.Contains("get-state")?"device":args.Contains("dumpsys")?dump:"",Exit=0};},ms=>events.Add("delay:"+ms),p=>{});
 check(events.Last().EndsWith("HW91")&&!events.Last().EndsWith("HW15"),"Selected HDMI overrides legacy hardware URI");
 check(events.IndexOf("delay:3000")<events.FindIndex(v=>v.Contains("dumpsys")),"Discover input after wake delay");
 failed=false;try{ResolveInput(s,(args,input,timeout)=>new Reply{Exit=0,Text=""});}catch(InvalidOperationException){failed=true;}check(failed,"Unknown mapping cannot reuse stale hardware URI");
 s.GoogleTvInputUri="";check(ResolveInput(s,(args,input,timeout)=>new Reply{Exit=1,Text="permission denied"})=="input keyevent 244","Generic HDMI key fallback");
 s.GoogleTvInputUri="content://android.media.tv/passthrough/custom%2Finput";check(ResolveInput(s,(args,input,timeout)=>{throw new Exception("Custom override should not query");}).EndsWith(s.GoogleTvInputUri),"Explicit custom override retained");
 s.GoogleTvInputUri="content://android.media.tv/passthrough/com.tcl.tvinput%2F.Service%2FHW15";s.GoogleTvInputUri+=";reboot";failed=false;try{Validate(s);}catch(InvalidOperationException){failed=true;}check(failed,"Reject injected input command");var sleepCommands=new List<string>();StandbyCore("192.0.2.10",(args,input,timeout)=>{sleepCommands.Add(args);return new Reply{Exit=0,Text=""};});check(sleepCommands.SequenceEqual(new[]{"-s 192.0.2.10:5555 shell input keyevent 223"}),"Standby uses sleep, never power toggle");bool standbyError=false;try{StandbyCore("192.0.2.10",(args,input,timeout)=>new Reply{Exit=1,Text="offline"});}catch(InvalidOperationException){standbyError=true;}check(standbyError,"Standby errors reported");check(!new Settings().GoogleTvPowerOff,"TV standby defaults off");File.WriteAllText(Storage.PathOf("google-tv-test.txt"),"PASS: bundled ADB loads; endpoint validation; modern connection ports; wake packet; wake/input ordering; authorization failures; automatic HDMI discovery; selected port overrides stale hardware URI; generic fallback and explicit custom override. No network TV commands were sent.");}
}
}
