using System;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
using System.Threading.Tasks;
namespace TVLounge {
public partial class MainForm {
 CheckBox googleTvPowerOff=new CouchCheckBox{Text="Turn off TV when returning to desktop"};ModernButton googleConnect,googlePair,googleTest;Card googleTvCard=new Card();ModernSwitch googleTvEnabled=new ModernSwitch();TextBox googleTvHost=GoogleTvDialog.Box(),googleTvMac=GoogleTvDialog.Box(),googleTvUri=GoogleTvDialog.Box();DarkCombo googleTvInput=new DarkCombo(),googleTvDelay=new DarkCombo();
 void AddGoogleTv(){Theme.Place(content,googleTvCard,32,594,808,486);Theme.Place(googleTvCard,Theme.Label("Google TV — control over your network",12,true,Theme.Text),24,16,690,28);Theme.Place(googleTvCard,googleTvEnabled,738,18,46,28);googleTvEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;googleTvEnabled.AccessibleName="Enable Google TV network wake and input control";
 Theme.Place(googleTvCard,Theme.Label("ADB is included. Enable debugging on the TV, then connect and allow this PC. No CEC adapter needed.",9,false,Theme.Muted),24,50,760,41);
 Theme.Place(googleTvCard,Theme.Label("TV IP ADDRESS (:PORT IF SHOWN)",8,true,Theme.Muted),24,97,360,20);Theme.Place(googleTvCard,googleTvHost,24,123,350,32);Theme.Place(googleTvCard,Theme.Label("MAC ADDRESS — OPTIONAL WAKE",8,true,Theme.Muted),400,97,380,20);Theme.Place(googleTvCard,googleTvMac,400,123,384,32);googleTvMac.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;
 for(int i=1;i<=4;i++)googleTvInput.Items.Add(new Choice(i.ToString(),"HDMI "+i));for(int i=0;i<=30;i++)googleTvDelay.Items.Add(new Choice(i.ToString(),i+" seconds"));Theme.Place(googleTvCard,googleTvInput,24,177,270,36);Theme.Place(googleTvCard,googleTvDelay,310,177,220,36);Theme.Place(googleTvCard,Theme.Label("ADVANCED INPUT URI — LEAVE BLANK FOR AUTOMATIC HDMI",8,true,Theme.Muted),24,224,750,20);Theme.Place(googleTvCard,googleTvUri,24,249,760,32);googleTvUri.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;
 var connect=googleConnect=new ModernButton{Text="Connect / authorize"};var pair=googlePair=new ModernButton{Text="Pair with code"};var test=googleTest=new ModernButton{Text="Test TV power & input"};Theme.Place(googleTvCard,connect,24,309,238,38);Theme.Place(googleTvCard,pair,276,309,220,38);Theme.Place(googleTvCard,test,510,309,274,38);test.Anchor=AnchorStyles.Top|AnchorStyles.Right;connect.Click+=async delegate{var s=ReadGoogleTv();await GoogleTvAction(()=>GoogleTv.Connect(s),"TV connected. Save settings to use network control in TV mode.");};test.Click+=async delegate{var s=ReadGoogleTv();await GoogleTvAction(()=>GoogleTv.Wake(s),"TV wake and input commands sent. Check the TV picture and HDMI input.");};pair.Click+=async delegate{var s=ReadGoogleTv();using(var dialog=new GoogleTvPairDialog(s.GoogleTvHost)){dialog.Icon=Icon;if(dialog.ShowDialog(this)==DialogResult.OK){string endpoint=dialog.Endpoint,code=dialog.Code;await GoogleTvAction(()=>GoogleTv.Pair(s,endpoint,code),"TV paired. Use Connect / authorize with the connection port shown on the TV.");}}};
 var guide=new ModernButton{Text="TV setup guide"};Theme.Place(googleTvCard,guide,24,357,760,36);guide.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;guide.Click+=delegate{using(var tutorial=new GoogleTvGuide()){tutorial.Icon=Icon;tutorial.ShowDialog(this);}};Theme.Place(googleTvCard,googleTvPowerOff,24,411,760,28);googleTvPowerOff.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;Theme.Place(googleTvCard,Theme.Label("Puts the TV into standby after desktop restoration. Applies to the next TV session.",9,false,Theme.Muted),24,446,760,28);googleTvEnabled.CheckedChanged+=delegate{googleTvPowerOff.Enabled=googleTvEnabled.Checked;if(googleTvEnabled.Checked)cecEnabled.Checked=false;};cecEnabled.CheckedChanged+=delegate{if(cecEnabled.Checked)googleTvEnabled.Checked=false;};SetGoogleTv(settings);CaptureLayout(googleTvCard);}
 async Task GoogleTvAction(Action action,string success){if(busy||installingUpdate||uiTest)return;bool done=false;status.Text="Connecting to TV. If asked, allow this PC on the TV...";await Work(()=>{action();done=true;},false);if(done)status.Text=success;}
 Settings ReadGoogleTv(){var s=Clone(settings);s.GoogleTvPowerOff=googleTvPowerOff.Checked;s.GoogleTvEnabled=googleTvEnabled.Checked;s.GoogleTvHost=googleTvHost.Text.Trim();s.GoogleTvMac=googleTvMac.Text.Trim();s.GoogleTvInputUri=googleTvUri.Text.Trim();s.GoogleTvHdmiPort=int.Parse(((Choice)googleTvInput.SelectedItem).Id);s.GoogleTvWakeDelay=int.Parse(((Choice)googleTvDelay.SelectedItem).Id);return s;}
 void SaveGoogleTv(Settings s){var n=ReadGoogleTv();s.GoogleTvPowerOff=n.GoogleTvPowerOff;s.GoogleTvEnabled=n.GoogleTvEnabled;s.GoogleTvHost=n.GoogleTvHost;s.GoogleTvMac=n.GoogleTvMac;s.GoogleTvInputUri=n.GoogleTvInputUri;s.GoogleTvHdmiPort=n.GoogleTvHdmiPort;s.GoogleTvWakeDelay=n.GoogleTvWakeDelay;if(s.GoogleTvEnabled){s.CecEnabled=false;if(!uiTest)GoogleTv.Validate(s);}}
 void SetGoogleTv(Settings s){googleTvPowerOff.Checked=s.GoogleTvPowerOff;googleTvEnabled.Checked=s.GoogleTvEnabled;googleTvPowerOff.Enabled=s.GoogleTvEnabled;googleTvHost.Text=s.GoogleTvHost;googleTvMac.Text=s.GoogleTvMac;googleTvUri.Text=GoogleTv.HardwareUri(s.GoogleTvInputUri)?"":s.GoogleTvInputUri;googleTvInput.SelectedItem=googleTvInput.Items[Math.Max(0,Math.Min(3,s.GoogleTvHdmiPort-1))];googleTvDelay.SelectedItem=googleTvDelay.Items[Math.Max(0,Math.Min(30,s.GoogleTvWakeDelay))];}
 void LayoutGoogleTv(int width){googleTvCard.SetBounds(Theme.Px(this,32),Theme.Px(this,594),width-Theme.Px(this,64),Theme.Px(this,486));googleTvCard.Visible=currentPage==1;PlaceLogicalChildren(googleTvCard);int margin=Theme.Px(this,24),gap=Theme.Px(this,12),buttonWidth=(googleTvCard.ClientSize.Width-2*margin-2*gap)/3;int index=0;foreach(var button in new[]{googleConnect,googlePair,googleTest})button.SetBounds(margin+(buttonWidth+gap)*index++,Theme.Px(this,309),buttonWidth,Theme.Px(this,38));}
 void CheckGoogleTvBindings(){string path=Storage.PathOf("settings.json"),original=System.IO.File.ReadAllText(path);var before=Clone(settings);try{googleTvEnabled.Checked=true;googleTvPowerOff.Checked=true;googleTvHost.Text="192.168.1.99:37123";googleTvUri.Text="content://android.media.tv/passthrough/com.tcl.tvinput%2F.Service%2FHW15";SetGoogleTv(ReadGoogleTv());if(googleTvUri.Text!="")throw new Exception("Legacy hardware input URI must migrate to automatic selection");googleTvInput.SelectedItem=googleTvInput.Items[2];Save();var saved=Storage.Read<Settings>("settings.json");if(!saved.GoogleTvPowerOff||!saved.GoogleTvEnabled||saved.CecEnabled||saved.GoogleTvHost!=googleTvHost.Text||saved.GoogleTvHdmiPort!=3)throw new Exception("Google TV settings did not persist");}finally{System.IO.File.WriteAllText(path,original);settings=before;SetCec(before);SetGoogleTv(before);}}
}
internal sealed class GoogleTvPairDialog : Form {
 TextBox endpoint=GoogleTvDialog.Box(),code=GoogleTvDialog.Box();public string Endpoint {get{return endpoint.Text.Trim();}}public string Code{get{return code.Text.Trim();}}
 public GoogleTvPairDialog(string host){Text="SteamCouch — Pair Google TV";BackColor=Theme.Background;ForeColor=Theme.Text;ClientSize=new Size(620,320);StartPosition=FormStartPosition.CenterParent;AutoScaleMode=AutoScaleMode.Dpi;AutoScaleDimensions=new SizeF(96,96);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;Theme.Place(this,Theme.Label("On the TV: Wireless debugging → Pair using pairing code. Enter its pairing address and code. The connection port is different.",10,false,Theme.Muted),24,20,568,75);endpoint.Text=(host??"").Split(':')[0]+":";Theme.Place(this,Theme.Label("PAIRING IP:PORT",8,true,Theme.Accent),24,110,560,20);Theme.Place(this,endpoint,24,139,568,32);Theme.Place(this,Theme.Label("SIX-DIGIT CODE",8,true,Theme.Accent),24,184,560,20);code.MaxLength=6;code.UseSystemPasswordChar=true;Theme.Place(this,code,24,213,220,32);var pair=new ModernButton{Text="Pair",Primary=true};Theme.Place(this,pair,424,266,168,38);pair.Click+=delegate{DialogResult=DialogResult.OK;Close();};AcceptButton=pair;Shown+=delegate{Theme.DarkTitle(this);};}
}
internal sealed class GoogleTvDialog : Form {
 CheckBox turnOff=new CouchCheckBox{Text="Turn off TV when returning to desktop"};public Settings Result;ModernSwitch enabled=new ModernSwitch();TextBox host=Box();DarkCombo input=new DarkCombo();Label info=Theme.Label("TV: Settings → System → About → Android TV OS build: press OK seven times. Then System → Developer options → USB/network debugging. For Wireless debugging, pair first and use its connection port.",10,false,Theme.Muted);bool working;
 public static TextBox Box(){return new TextBox{BackColor=Theme.Input,ForeColor=Theme.Text,BorderStyle=BorderStyle.FixedSingle};}
 public GoogleTvDialog(Settings s){Result=s;Text="SteamCouch — Google TV setup";BackColor=Theme.Background;ForeColor=Theme.Text;ClientSize=new Size(680,440);StartPosition=FormStartPosition.CenterParent;AutoScaleMode=AutoScaleMode.Dpi;AutoScaleDimensions=new SizeF(96,96);MinimizeBox=false;MaximizeBox=false;Theme.Place(this,Theme.Label("Wake TV & select HDMI over your network",17,true,Theme.Text),24,20,624,48);Theme.Place(this,enabled,602,76,46,28);Theme.Place(this,Theme.Label("Use Google TV network control",11,true,Theme.Text),24,78,560,28);enabled.Checked=s.GoogleTvEnabled;Theme.Place(this,info,24,118,624,70);Theme.Place(this,Theme.Label("TV IP ADDRESS (:PORT IF SHOWN)",8,true,Theme.Accent),24,198,624,20);host.Text=s.GoogleTvHost;Theme.Place(this,host,24,229,395,32);for(int i=1;i<=4;i++)input.Items.Add(new Choice(i.ToString(),"HDMI "+i));input.SelectedItem=input.Items[Math.Max(0,Math.Min(3,s.GoogleTvHdmiPort-1))];Theme.Place(this,input,440,227,208,36);var connect=new ModernButton{Text="Connect / authorize"};var pair=new ModernButton{Text="Pair with code"};var done=new ModernButton{Text="Save TV setup",Primary=true};Theme.Place(this,connect,24,292,252,38);Theme.Place(this,pair,292,292,208,38);Theme.Place(this,done,428,373,220,38);var guide=new ModernButton{Text="TV setup guide"};Theme.Place(this,guide,24,373,220,38);guide.Click+=delegate{using(var tutorial=new GoogleTvGuide()){tutorial.Icon=Icon;tutorial.ShowDialog(this);}};Theme.Place(this,turnOff,24,336,624,28);turnOff.Checked=s.GoogleTvPowerOff;turnOff.Enabled=enabled.Checked;enabled.CheckedChanged+=delegate{turnOff.Enabled=enabled.Checked;};connect.Click+=async delegate{var snapshot=Read();await Do(()=>GoogleTv.Connect(snapshot));};pair.Click+=async delegate{using(var dialog=new GoogleTvPairDialog(host.Text)){dialog.Icon=Icon;if(dialog.ShowDialog(this)==DialogResult.OK){var snapshot=Read();string endpoint=dialog.Endpoint,code=dialog.Code;await Do(()=>GoogleTv.Pair(snapshot,endpoint,code));}}};done.Click+=delegate{try{Result=Read();if(Result.GoogleTvEnabled)GoogleTv.Validate(Result);DialogResult=DialogResult.OK;Close();}catch(Exception e){info.Text=e.Message;}};FormClosing+=delegate(object sender,FormClosingEventArgs e){if(working)e.Cancel=true;};Shown+=delegate{Theme.DarkTitle(this);};}
 Settings Read(){var s=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<Settings>(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Result));s.GoogleTvPowerOff=turnOff.Checked;s.GoogleTvHost=host.Text.Trim();s.GoogleTvEnabled=enabled.Checked;s.GoogleTvHdmiPort=int.Parse(((Choice)input.SelectedItem).Id);if(GoogleTv.HardwareUri(s.GoogleTvInputUri))s.GoogleTvInputUri="";if(s.GoogleTvEnabled)s.CecEnabled=false;return s;}
 async Task Do(Action action){if(working)return;working=true;Enabled=false;info.Text="If prompted, allow this PC on the TV...";try{await Task.Run(action);info.Text="TV connection/pairing succeeded. Save TV setup to continue.";}catch(Exception e){info.Text=e.Message;}finally{working=false;Enabled=true;}}
}
}
