using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using System.Threading.Tasks;
namespace TVLounge {
public partial class MainForm {
 ModernSwitch autoReturn=new ModernSwitch(),allowSleep=new ModernSwitch(),gameProfilesEnabled=new ModernSwitch();Card couchOptionsCard=new Card(),extraActionsCard=new Card(),gameProfilesCard=new Card();TextBox playnitePath=new TextBox();DarkCombo gameProfileList=new DarkCombo();Label gameProfileInfo=Theme.Label("Off until enabled in Settings. Each game also has its own enable switch.",9,false,Theme.Muted);
 ModernSwitch[] actionEnabled=new ModernSwitch[3];DarkCombo[] actionChord=new DarkCombo[3],actionType=new DarkCombo[3];ControllerInput[] actionControllers=Enumerable.Range(0,3).Select(i=>new ControllerInput()).ToArray();
 List<GameProfile> gameProfiles=new List<GameProfile>();HashSet<uint> launcherRoots=new HashSet<uint>();HashSet<string> rejectedGames=new HashSet<string>(StringComparer.OrdinalIgnoreCase);System.Windows.Forms.Timer couchTimer=new System.Windows.Forms.Timer{Interval=2000};bool couchTick,sawLauncher,profilePrompt;DateTime? launcherClosed;bool lastActive;
 void AddOptionalFeatures(){
  Theme.Place(content,couchOptionsCard,32,948,808,314);
  Theme.Place(couchOptionsCard,Theme.Label("Return to desktop when the launcher closes",11,true,Theme.Text),24,16,670,28);Theme.Place(couchOptionsCard,autoReturn,738,18,46,28);autoReturn.Anchor=AnchorStyles.Top|AnchorStyles.Right;autoReturn.Checked=settings.AutoReturn;
  Theme.Place(couchOptionsCard,Theme.Label("Optional for Steam and Playnite. Waits while a launched game appears active.",9,false,Theme.Muted),24,50,750,27);
  Theme.Place(couchOptionsCard,Theme.Label("Show Sleep in the quick menu",11,true,Theme.Text),24,88,670,28);Theme.Place(couchOptionsCard,allowSleep,738,88,46,28);allowSleep.Anchor=AnchorStyles.Top|AnchorStyles.Right;allowSleep.Checked=settings.AllowSleep;
  Theme.Place(couchOptionsCard,Theme.Label("Requires confirmation. Restores desktop first; never forces a running game to close.",9,false,Theme.Muted),24,121,750,27);
  Theme.Place(couchOptionsCard,Theme.Label("Use per-game video profiles",11,true,Theme.Text),24,158,670,28);Theme.Place(couchOptionsCard,gameProfilesEnabled,738,158,46,28);gameProfilesEnabled.Anchor=AnchorStyles.Top|AnchorStyles.Right;gameProfilesEnabled.Checked=settings.GameProfilesEnabled;
  Theme.Place(couchOptionsCard,Theme.Label("Manage games in Profiles. Changes require confirmation and revert when a game closes.",9,false,Theme.Muted),24,191,750,27);
  Theme.Place(couchOptionsCard,Theme.Label("PLAYNITE PROGRAM — ONLY USED IF PLAYNITE IS SELECTED",8,true,Theme.Muted),24,236,740,24);playnitePath.Text=settings.PlaynitePath;playnitePath.BackColor=Theme.Input;playnitePath.ForeColor=Theme.Text;playnitePath.BorderStyle=BorderStyle.FixedSingle;Theme.Place(couchOptionsCard,playnitePath,24,271,584,32);playnitePath.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;var browsePlaynite=new ModernButton{Text="Browse"};Theme.Place(couchOptionsCard,browsePlaynite,626,267,158,38);browsePlaynite.Anchor=AnchorStyles.Top|AnchorStyles.Right;browsePlaynite.Click+=delegate{using(var picker=new OpenFileDialog{Filter="Playnite program|Playnite.FullscreenApp.exe;Playnite.DesktopApp.exe",FileName=playnitePath.Text})if(picker.ShowDialog(this)==DialogResult.OK)playnitePath.Text=picker.FileName;};
  Theme.Place(content,extraActionsCard,32,1274,808,292);Theme.Place(extraActionsCard,Theme.Label("Additional controller actions",12,true,Theme.Text),24,16,700,28);Theme.Place(extraActionsCard,Theme.Label("Each action is optional. Enabled shortcuts must use different combinations.",9,false,Theme.Muted),24,51,740,28);
  var saved=settings.ControllerActions??OptionalPolicy.Defaults();for(int i=0;i<3;i++){var binding=i<saved.Count?saved[i]:OptionalPolicy.Defaults()[i];actionEnabled[i]=new ModernSwitch{Checked=binding.Enabled};actionChord[i]=new DarkCombo();actionType[i]=new DarkCombo();foreach(var c in new[]{new Choice("4128","Select + A"),new Choice("8224","Select + B"),new Choice("16416","Select + X"),new Choice("32800","Select + Y")})actionChord[i].Items.Add(c);foreach(var c in new[]{new Choice("Mute","Mute / unmute"),new Choice("VolumeUp","Volume +5%"),new Choice("VolumeDown","Volume −5%"),new Choice("Desktop","Return to desktop"),new Choice("Sleep","Confirm PC sleep")})actionType[i].Items.Add(c);actionChord[i].SelectedItem=actionChord[i].Items.Cast<Choice>().FirstOrDefault(c=>c.Id==binding.Mask.ToString())??actionChord[i].Items[0];actionType[i].SelectedItem=actionType[i].Items.Cast<Choice>().FirstOrDefault(c=>c.Id==binding.Action)??actionType[i].Items[0];Theme.Place(extraActionsCard,actionChord[i],24,90+i*50,270,38);Theme.Place(extraActionsCard,actionType[i],310,90+i*50,386,38);actionType[i].Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;Theme.Place(extraActionsCard,actionEnabled[i],738,95+i*50,46,28);actionEnabled[i].Anchor=AnchorStyles.Top|AnchorStyles.Right;int slot=i;actionChord[i].Enabled=actionType[i].Enabled=actionEnabled[i].Checked;actionEnabled[i].CheckedChanged+=delegate{actionChord[slot].Enabled=actionType[slot].Enabled=actionEnabled[slot].Checked;};}
  var test=new ModernButton{Text="Test controller"};Theme.Place(extraActionsCard,test,24,244,195,36);test.Click+=delegate{TestController();};Theme.Place(extraActionsCard,Theme.Label("New actions work in TV mode. Hold briefly, then release.",9,false,Theme.Muted),240,245,540,34);
  Theme.Place(content,gameProfilesCard,32,332,808,222);Theme.Place(gameProfilesCard,Theme.Label("Per-game video profiles",12,true,Theme.Text),24,16,730,28);Theme.Place(gameProfilesCard,gameProfileInfo,24,51,740,44);gameProfileInfo.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;Theme.Place(gameProfilesCard,gameProfileList,24,107,760,38);gameProfileList.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;
  try{gameProfiles=GameProfiles.Load();}catch(Exception e){Storage.Log(e.ToString());gameProfileInfo.Text="Saved game profiles could not be read. Current settings are unchanged.";}ReloadGameProfiles();var add=new ModernButton{Text="Add game",Primary=true};var edit=new ModernButton{Text="Edit game"};var remove=new ModernButton{Text="Remove game"};Theme.Place(gameProfilesCard,add,24,163,180,38);Theme.Place(gameProfilesCard,edit,216,163,180,38);Theme.Place(gameProfilesCard,remove,408,163,180,38);add.Click+=async delegate{await EditGame(null);};edit.Click+=async delegate{await EditGame(gameProfileList.SelectedItem as GameProfile);};remove.Click+=delegate{if(engine.Active||busy){ShowError(new InvalidOperationException("Return to desktop before removing game profiles."));return;}var selected=gameProfileList.SelectedItem as GameProfile;if(selected==null)return;var next=gameProfiles.Where(p=>p!=selected).ToList();Storage.Save("game-profiles.json",next);gameProfiles=next;ReloadGameProfiles();};
  CaptureLayout(couchOptionsCard);CaptureLayout(extraActionsCard);CaptureLayout(gameProfilesCard);couchTimer.Tick+=async delegate{if(couchTick||uiTest)return;couchTick=true;try{await WatchCouch();}catch(Exception e){Storage.Log(e.ToString());status.Text=e.Message;}finally{couchTick=false;}};
 }
 void CheckOptionalBindings(){string file=Storage.PathOf("settings.json"),original=File.ReadAllText(file);var before=Clone(settings);try{autoReturn.Checked=!before.AutoReturn;allowSleep.Checked=!before.AllowSleep;gameProfilesEnabled.Checked=!before.GameProfilesEnabled;for(int i=0;i<3;i++)actionEnabled[i].Checked=false;Save();var saved=Storage.Read<Settings>("settings.json");if(saved.AutoReturn==before.AutoReturn||saved.AllowSleep==before.AllowSleep||saved.GameProfilesEnabled==before.GameProfilesEnabled||saved.ControllerActions.Any(a=>a.Enabled))throw new Exception("Optional settings did not persist");}finally{File.WriteAllText(file,original);settings=before;autoReturn.Checked=before.AutoReturn;allowSleep.Checked=before.AllowSleep;gameProfilesEnabled.Checked=before.GameProfilesEnabled;for(int i=0;i<3;i++){var b=before.ControllerActions[i];actionEnabled[i].Checked=b.Enabled;actionChord[i].SelectedItem=actionChord[i].Items.Cast<Choice>().First(c=>c.Id==b.Mask.ToString());actionType[i].SelectedItem=actionType[i].Items.Cast<Choice>().First(c=>c.Id==b.Action);}UpdateMode();}}
 void PreviewOptionalFeatures(){SelectPage(2);panel.ScrollControlIntoView(couchOptionsCard);Application.DoEvents();using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,new Rectangle(0,0,Width,Height));b.Save(Storage.PathOf("optional-settings.png"));}panel.ScrollControlIntoView(extraActionsCard);Application.DoEvents();using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,new Rectangle(0,0,Width,Height));b.Save(Storage.PathOf("action-editor.png"));}using(var tester=new ControllerTester()){tester.Show(this);Application.DoEvents();using(var b=new Bitmap(tester.Width,tester.Height)){tester.DrawToBitmap(b,new Rectangle(0,0,b.Width,b.Height));b.Save(Storage.PathOf("controller-tester.png"));}tester.Close();}using(var editor=new GameProfileEditor(new GameProfile{Name="Example game",Executable=Application.ExecutablePath,Hdr="On"},new List<VideoMode>{new VideoMode{Width=3840,Height=2160,Frequency=120}})){editor.Show(this);Application.DoEvents();using(var b=new Bitmap(editor.Width,editor.Height)){editor.DrawToBitmap(b,new Rectangle(0,0,b.Width,b.Height));b.Save(Storage.PathOf("game-profile-editor.png"));}editor.Close();}using(var menu=new QuickMenuWindow(devices,Screen.FromControl(this).DeviceName,()=>Task.FromResult(0),true,true,()=>Task.FromResult(0))){menu.Show(this);menu.WriteOptionalPreviews().GetAwaiter().GetResult();menu.Close();}}
 void LayoutOptionalFeatures(int width){var cards=new[]{couchOptionsCard,extraActionsCard,gameProfilesCard};int[] ys={948,1274,332},heights={314,292,222},pages={2,2,3};for(int i=0;i<cards.Length;i++){cards[i].SetBounds(Theme.Px(this,32),Theme.Px(this,ys[i]),width-Theme.Px(this,64),Theme.Px(this,heights[i]));cards[i].Visible=currentPage==pages[i];PlaceLogicalChildren(cards[i]);}if(currentPage==2)content.Height=extraActionsCard.Bottom+Theme.Px(this,8);if(currentPage==3)content.Height=gameProfilesCard.Bottom+Theme.Px(this,8);}
 void SaveOptional(Settings next){next.AutoReturn=autoReturn.Checked;next.AllowSleep=allowSleep.Checked;next.GameProfilesEnabled=gameProfilesEnabled.Checked;next.PlaynitePath=playnitePath.Text.Trim();next.ControllerActions=new List<ControllerActionBinding>();for(int i=0;i<3;i++)next.ControllerActions.Add(new ControllerActionBinding{Enabled=actionEnabled[i].Checked&&(((Choice)actionType[i].SelectedItem).Id!="Sleep"||next.AllowSleep),Mask=int.Parse(((Choice)actionChord[i].SelectedItem).Id),Action=((Choice)actionType[i].SelectedItem).Id});OptionalPolicy.Validate(next);if(next.LaunchSteam&&next.Launcher=="Playnite")PlayniteClient.Validate(next.PlaynitePath);if(!uiTest&&settings.GameProfilesEnabled&&!next.GameProfilesEnabled&&GameProfiles.Active){if(OwnedForms.Length>0)throw new InvalidOperationException("Close the quick menu before disabling game profiles.");GameProfiles.Restore();}foreach(var controller in actionControllers)controller.Reset();for(int i=0;i<3;i++)actionEnabled[i].Checked=next.ControllerActions[i].Enabled;sawLauncher=false;launcherClosed=null;rejectedGames.Clear();}
 async Task PollActions(){for(int i=0;i<3;i++){var binding=(settings.ControllerActions??OptionalPolicy.Defaults()).ElementAtOrDefault(i)??OptionalPolicy.Defaults()[i];bool fire=actionControllers[i].PollMilliseconds(binding.Enabled&&engine.Active,binding.Mask,500,busy||installingUpdate||OwnedForms.Length>0||profilePrompt);if(!fire)continue;if(binding.Action=="Desktop")await Work(()=>engine.Restore(settings.TimeoutSeconds),true);else if(binding.Action=="Sleep"){if(settings.AllowSleep)OpenSleepMenu();}else await Work(()=>{using(var v=new SessionVolume()){if(binding.Action=="Mute")v.Muted=!v.Muted;else v.Percent=v.Percent+(binding.Action=="VolumeUp"?5:-5);}},false);break;}}
 void ReloadGameProfiles(){gameProfileList.Items.Clear();foreach(var p in gameProfiles)gameProfileList.Items.Add(p);if(gameProfileList.Items.Count>0)gameProfileList.SelectedItem=gameProfileList.Items[0];}
 async Task EditGame(GameProfile original){if(busy){ShowError(new InvalidOperationException("Wait for the current operation before editing game profiles."));return;}try{List<VideoMode> modes=await Task.Run(()=>{var row=devices.Monitors().FirstOrDefault(m=>m.Get("Monitor ID")==settings.MonitorId&&Engine.IsOn(m));return row==null?new List<VideoMode>():VideoNative.Modes(row.Get("Name"));});using(var dialog=new GameProfileEditor(original,modes)){dialog.Icon=Icon;if(dialog.ShowDialog(this)!=DialogResult.OK)return;var profile=dialog.Result;if(gameProfiles.Any(p=>p!=original&&string.Equals(p.Executable,profile.Executable,StringComparison.OrdinalIgnoreCase)))throw new InvalidOperationException("A profile already exists for that game executable.");var next=gameProfiles.Where(p=>p!=original).ToList();next.Add(profile);Storage.Save("game-profiles.json",next);gameProfiles=next;ReloadGameProfiles();}}catch(Exception e){ShowError(e);}}
 void TestController(){foreach(var controller in actionControllers)controller.Reset();controllers.Reset();menuControllers.Reset();using(var tester=new ControllerTester()){tester.Icon=Icon;tester.ShowDialog(this);}foreach(var controller in actionControllers)controller.Reset();controllers.Reset();menuControllers.Reset();}
 void OpenSleepMenu(){OpenQuickMenu(false);if(quickMenu!=null)quickMenu.RequestSleep();}
 async Task SleepAfterRestore(){if(!settings.AllowSleep)return;await Work(()=>engine.Restore(settings.TimeoutSeconds),true);if(engine.Active||GameProfiles.Active||System.IO.File.Exists(Storage.PathOf("pending-video.json"))||System.IO.File.Exists(Storage.PathOf("video-session.json")))return;try{CouchPower.Sleep();}catch(Exception e){ShowError(e);}}
 async Task WatchCouch(){bool active=engine.Active;if(active!=lastActive){lastActive=active;sawLauncher=false;launcherClosed=null;launcherRoots.Clear();rejectedGames.Clear();}if(!active||busy||installingUpdate||OwnedForms.Length>0||profilePrompt)return;var saved=Storage.Read<Snapshot>("restore.json");if(settings.GameProfilesEnabled){var running=await Task.Run(()=>GameProfiles.Running(gameProfiles));rejectedGames.RemoveWhere(path=>!running.Any(p=>string.Equals(p.Executable,path,StringComparison.OrdinalIgnoreCase)));if(GameProfiles.Active){var current=GameProfiles.State;if(!running.Any(p=>string.Equals(p.Executable,current.Executable,StringComparison.OrdinalIgnoreCase)))await Work(()=>GameProfiles.Restore(),false);}else if(running.Count==1&&!rejectedGames.Contains(running[0].Executable)){var profile=running[0];rejectedGames.Add(profile.Executable);OpenQuickMenu(false);if(quickMenu!=null){profilePrompt=true;try{await quickMenu.ApplyProfile(profile);}finally{profilePrompt=false;}}return;}}
  if(!settings.AutoReturn||!saved.LauncherStarted||saved.Launcher=="Xbox")return;bool open=saved.Launcher=="Playnite"?PlayniteClient.Running:SteamClient.IsBigPictureOpen();if(open){sawLauncher=true;launcherClosed=null;launcherRoots.UnionWith(GameActivity.LauncherIds());return;}if(!sawLauncher)return;bool gameRunning=await Task.Run(()=>GameActivity.Any(launcherRoots));if(gameRunning){launcherClosed=null;return;}if(!launcherClosed.HasValue)launcherClosed=DateTime.UtcNow;if(OptionalPolicy.AutoReturnEligible(settings.AutoReturn,engine.Active,sawLauncher,open,busy||OwnedForms.Length>0,gameRunning,launcherClosed,DateTime.UtcNow))await Work(()=>engine.Restore(settings.TimeoutSeconds),true);
 }
}
internal sealed class ControllerTester : Form {
 Label state=Theme.Label("Connect a controller, then press its buttons.",12,true,Theme.Text);System.Windows.Forms.Timer timer=new System.Windows.Forms.Timer{Interval=80};
 public ControllerTester(){Text="SteamCouch — Controller test";BackColor=Theme.Background;ForeColor=Theme.Text;ClientSize=new Size(690,360);StartPosition=FormStartPosition.CenterParent;AutoScaleMode=AutoScaleMode.Dpi;AutoScaleDimensions=new SizeF(96,96);Theme.Place(this,Theme.Label("Test your controller",20,true,Theme.Text),24,18,630,48);Theme.Place(this,Theme.Label("Shortcuts are paused while this window is open. Xbox-button detection varies by driver.",10,false,Theme.Muted),24,78,630,55);Theme.Place(this,state,24,149,630,138);var close=new ModernButton{Text="Done",Primary=true};Theme.Place(this,close,500,308,164,38);close.Click+=delegate{Close();};timer.Tick+=delegate{var lines=new List<string>();for(uint i=0;i<4;i++){string value=ControllerInput.Describe(i);if(value!=null)lines.Add("Controller "+(i+1)+": "+value);}state.Text=lines.Count==0?"No compatible controller detected.":string.Join("\n",lines);};Shown+=delegate{Theme.DarkTitle(this);timer.Start();};FormClosed+=delegate{timer.Stop();timer.Dispose();};}
}
internal sealed class GameProfileEditor : Form {
 public GameProfile Result;TextBox name=new TextBox(),path=new TextBox();ModernSwitch enabled=new ModernSwitch();DarkCombo hdr=new DarkCombo(),mode=new DarkCombo();
 public GameProfileEditor(GameProfile original,List<VideoMode> modes){original=original??new GameProfile();Text="SteamCouch — Game profile";BackColor=Theme.Background;ForeColor=Theme.Text;Font=new Font("Segoe UI",10);ClientSize=new Size(720,530);StartPosition=FormStartPosition.CenterParent;AutoScaleMode=AutoScaleMode.Dpi;AutoScaleDimensions=new SizeF(96,96);MinimizeBox=false;MaximizeBox=false;Theme.Place(this,Theme.Label("Game video profile",21,true,Theme.Text),24,16,670,45);Theme.Place(this,Theme.Label("Enabled for this game",11,true,Theme.Text),24,72,550,28);Theme.Place(this,enabled,648,72,46,28);enabled.Checked=original.Enabled;
  foreach(var field in new[]{name,path}){field.BackColor=Theme.Input;field.ForeColor=Theme.Text;field.BorderStyle=BorderStyle.FixedSingle;}name.MaxLength=64;name.Text=original.Name;path.Text=original.Executable;Theme.Place(this,Theme.Label("PROFILE NAME",8,true,Theme.Muted),24,113,600,22);Theme.Place(this,name,24,140,670,32);Theme.Place(this,Theme.Label("ACTUAL GAME EXECUTABLE",8,true,Theme.Muted),24,190,600,22);Theme.Place(this,path,24,217,510,32);var browse=new ModernButton{Text="Browse"};Theme.Place(this,browse,550,214,144,38);browse.Click+=delegate{using(var picker=new OpenFileDialog{Filter="Game executable|*.exe",FileName=path.Text})if(picker.ShowDialog(this)==DialogResult.OK){path.Text=picker.FileName;if(string.IsNullOrWhiteSpace(name.Text))name.Text=Path.GetFileNameWithoutExtension(path.Text);}};
  foreach(var c in new[]{new Choice("Keep","Keep current HDR"),new Choice("On","HDR on"),new Choice("Off","HDR off")})hdr.Items.Add(c);hdr.SelectedItem=hdr.Items.Cast<Choice>().First(c=>c.Id==original.Hdr);Theme.Place(this,hdr,24,275,670,38);mode.Items.Add(new Choice("Keep","Keep current resolution and refresh rate"));foreach(var m in modes)mode.Items.Add(m);var selected=modes.FirstOrDefault(m=>m.Width==original.Width&&m.Height==original.Height&&m.Frequency==original.Frequency);if(original.Width!=0&&selected.Width==0){selected=new VideoMode{Width=original.Width,Height=original.Height,Frequency=original.Frequency};mode.Items.Add(selected);}mode.SelectedItem=original.Width==0?mode.Items[0]:(object)selected;Theme.Place(this,mode,24,330,670,38);Theme.Place(this,Theme.Label(modes.Count==0?"Connect the TV and refresh devices to choose its supported display modes. HDR can still be saved.":"Applies only in TV mode when enabled in Settings. Confirm changes within 20 seconds.",9,false,Theme.Muted),24,386,670,58);var save=new ModernButton{Text="Save profile",Primary=true};Theme.Place(this,save,510,472,184,38);save.Click+=delegate{try{var video=mode.SelectedItem is VideoMode?(VideoMode)mode.SelectedItem:new VideoMode();Result=new GameProfile{Enabled=enabled.Checked,Name=name.Text.Trim(),Executable=path.Text.Trim(),Hdr=((Choice)hdr.SelectedItem).Id,Width=video.Width,Height=video.Height,Frequency=video.Frequency};OptionalPolicy.ValidateGame(Result);DialogResult=DialogResult.OK;Close();}catch(Exception e){MessageBox.Show(this,e.Message,"SteamCouch");}};Shown+=delegate{Theme.DarkTitle(this);};}
}
}
