using System;
using System.Linq;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Collections.Generic;
using System.Windows.Forms;
namespace TVLounge {
internal sealed class PerformanceHud : Form {
 public FrameSnapshot Frames=new FrameSnapshot();public TelemetrySnapshot Hardware=new TelemetrySnapshot();public string Battery="Battery unavailable",CaptureStatus="",AppName="Game";Settings preferences=new Settings();float scale=1;int level=1;
 public PerformanceHud(){FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.Manual;AutoScaleMode=AutoScaleMode.None;ShowInTaskbar=false;TopMost=true;DoubleBuffered=true;BackColor=Color.FromArgb(20,26,31);AccessibleName="SteamCouch performance display";}
 protected override bool ShowWithoutActivation {get{return true;}}protected override CreateParams CreateParams {get{var p=base.CreateParams;p.ExStyle|=0x08000000|0x20|0x80|0x80000;return p;}}
 protected override void WndProc(ref Message m){if(m.Msg==0x84){m.Result=new IntPtr(-1);return;}if(m.Msg==0x21){m.Result=new IntPtr(3);return;}base.WndProc(ref m);}internal static float FitScale(float desired,int width,int height,int screenWidth,int screenHeight){return Math.Min(desired,Math.Min(screenWidth/(float)(width+32),screenHeight/(float)(height+32)));}internal static Rectangle Placement(Rectangle screen,int corner,int width,int height,int margin){width=Math.Min(width,screen.Width);height=Math.Min(height,screen.Height);margin=Math.Max(0,Math.Min(margin,Math.Min((screen.Width-width)/2,(screen.Height-height)/2)));return new Rectangle(corner%2==0?screen.Left+margin:screen.Right-width-margin,corner<2?screen.Top+margin:screen.Bottom-height-margin,width,height);}
 public void Configure(Settings settings,string display){preferences=settings;level=Math.Max(1,Math.Min(4,settings.PerformanceLevel));var screen=WindowPlacement.MonitorBounds(display);if(!screen.HasValue){Hide();return;}float dpi=1;using(var scope=new WindowPlacement.PhysicalScope()){var s=Screen.AllScreens.FirstOrDefault(x=>x.DeviceName==display);if(s!=null){IntPtr handle=NativeMonitor(s.Bounds.Left+1,s.Bounds.Top+1);uint x,y;if(handle!=IntPtr.Zero&&GetDpiForMonitor(handle,0,out x,out y)==0)dpi=x/96f;}}scale=Math.Max(.75f,Math.Min(4,dpi*settings.PerformanceScale/100f));int logicalWidth=level==1?190:level==2?330:410,logicalHeight=level==1?76:level==2?168:level==3?298:438;scale=FitScale(scale,logicalWidth,logicalHeight,screen.Value.Width,screen.Value.Height);int w=(int)(logicalWidth*scale),h=(int)(logicalHeight*scale);var bounds=Placement(screen.Value,settings.PerformanceCorner,w,h,(int)(16*scale));using(var scope=new WindowPlacement.PhysicalScope()){Bounds=bounds;}Opacity=Math.Max(.3,Math.Min(1,settings.PerformanceOpacity/100.0));if(!Visible)Show();EnsureTransparency();Invalidate();}
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern IntPtr MonitorFromPoint(Point point,uint flags);static IntPtr NativeMonitor(int x,int y){return MonitorFromPoint(new Point(x,y),2);}
 [System.Runtime.InteropServices.DllImport("shcore.dll")]static extern int GetDpiForMonitor(IntPtr monitor,int type,out uint x,out uint y);
 [System.Runtime.InteropServices.DllImport("user32.dll",EntryPoint="GetWindowLongW")]static extern int GetWindowLong(IntPtr window,int index);[System.Runtime.InteropServices.DllImport("user32.dll",EntryPoint="SetWindowLongW")]static extern int SetWindowLong(IntPtr window,int index,int value);[System.Runtime.InteropServices.DllImport("user32.dll")]static extern bool SetLayeredWindowAttributes(IntPtr window,uint key,byte alpha,uint flags);int lastAlpha=-1;protected override void OnHandleCreated(EventArgs e){base.OnHandleCreated(e);lastAlpha=-1;EnsureTransparency();}void EnsureTransparency(){if(!IsHandleCreated)return;int style=GetWindowLong(Handle,-20),wanted=style|0x080800a0;if(style!=wanted){SetWindowLong(Handle,-20,wanted);lastAlpha=-1;}int alpha=(int)Math.Round(Opacity*255);if(lastAlpha!=alpha){SetLayeredWindowAttributes(Handle,0,(byte)alpha,2);lastAlpha=alpha;}}internal bool NativeStylesCorrect {get{return (GetWindowLong(Handle,-20)&0x080800a0)==0x080800a0;}}void Line(Graphics g,string text,int y,int size,bool bold,Color color){using(var f=new Font("Segoe UI",size*scale, bold?FontStyle.Bold:FontStyle.Regular,GraphicsUnit.Pixel))TextRenderer.DrawText(g,text,f,new Rectangle((int)(14*scale),(int)(y*scale),Width-(int)(28*scale),(int)((size+10)*scale)),color,TextFormatFlags.NoPrefix|TextFormatFlags.EndEllipsis);}
 static string Number(uint? value,string suffix){return value.HasValue?value.Value+suffix:"Unavailable";}static string Gib(ulong? value){return value.HasValue?(value.Value/1073741824.0).ToString("0.0")+" GB":"Unavailable";}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;using(var pen=new Pen(Theme.Accent,2*scale))g.DrawLine(pen,0,0,Width,0);Line(g,Frames.Fps.HasValue?Frames.Fps.Value.ToString("0")+" FPS":"FPS unavailable",10,26,true,Theme.Accent);Line(g,Frames.Fps.HasValue?AppName:CaptureStatus,43,11,false,Theme.Muted);if(level<2)return;int mask=preferences.PerformanceMetrics;if((mask&1)!=0){var rect=new RectangleF(14*scale,77*scale,(Width/scale-28)*scale,48*scale);using(var pen=new Pen(Theme.Border))g.DrawRectangle(pen,rect.X,rect.Y,rect.Width,rect.Height);if(Frames.Times.Length>1){double max=Math.Max(33.3,Frames.Times.Max());var points=Frames.Times.Select((v,i)=>new PointF(rect.X+i*rect.Width/(Frames.Times.Length-1),rect.Bottom-(float)(Math.Min(v,max)/max*rect.Height))).ToArray();using(var pen=new Pen(Theme.Accent,1.5f*scale))g.DrawLines(pen,points);}Line(g,Frames.Times.Length>0?Frames.Times.Last().ToString("0.0")+" ms / frame":"Frame time unavailable",126,11,false,Theme.Muted);}if((mask&2)!=0)Line(g,Battery,146,11,false,Theme.Text);if(level<3)return;var gpu=Hardware.Gpus.FirstOrDefault();int y=174;if((mask&4)!=0){Line(g,"CPU   "+(Hardware.Cpu.HasValue?Hardware.Cpu.Value.ToString("0")+"%":"Unavailable"),y,13,true,Theme.Text);y+=24;}if((mask&8)!=0){Line(g,"GPU   "+(gpu!=null?Number(gpu.Usage,"%"):"Unavailable"),y,13,true,Theme.Text);y+=24;}if((mask&16)!=0){Line(g,"Temp   CPU unavailable · GPU "+(gpu!=null?Number(gpu.Temperature,"°C"):"unavailable"),y,11,false,Theme.Muted);y+=24;}if((mask&32)!=0){Line(g,"Power   CPU unavailable · GPU "+(gpu!=null&&gpu.Watts.HasValue?gpu.Watts.Value.ToString("0.0")+" W":"unavailable"),y,11,false,Theme.Muted);y+=24;}if(level<4)return;y=Math.Max(278,y);if((mask&64)!=0){Line(g,"GPU clock   "+(gpu!=null?Number(gpu.Clock," MHz"):"Unavailable"),y,12,false,Theme.Text);y+=23;Line(g,"Memory clock   "+(gpu!=null?Number(gpu.MemoryClock," MHz"):"Unavailable"),y,12,false,Theme.Text);y+=23;}if((mask&128)!=0){Line(g,"RAM   "+Gib(Hardware.RamUsed)+" / "+Gib(Hardware.RamTotal),y,12,false,Theme.Text);y+=23;Line(g,"VRAM   "+(gpu!=null?Gib(gpu.Used)+" / "+Gib(gpu.Total):"Unavailable"),y,12,false,Theme.Text);y+=23;}if((mask&256)!=0&&Hardware.Cores.Length>0){int count=Hardware.Cores.Length;float width=(Width/scale-28)/count;for(int i=0;i<count;i++){using(var b=new SolidBrush(Theme.Accent))g.FillRectangle(b,(14+i*width)*scale,(y+22-Hardware.Cores[i]*.22f)*scale,Math.Max(1,(width-2)*scale),Math.Max(1,Hardware.Cores[i]*.22f*scale));}Line(g,"Per-core CPU activity",y+25,10,false,Theme.Muted);}}
}
}