using System;
using System.IO;
using System.IO.Pipes;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Runtime.InteropServices;
using System.Collections.Generic;
namespace TVLounge {
internal sealed class FrameSnapshot {public double? Fps;public double[] Times=new double[0];}
internal sealed class FrameTracker {
 sealed class Sample {public double Ms;public long Time;}
 readonly object gate=new object();readonly Dictionary<string,Queue<Sample>> chains=new Dictionary<string,Queue<Sample>>();string[] headers;int target;readonly Stopwatch clock=Stopwatch.StartNew();
 public void Target(int pid){lock(gate){if(target==pid)return;target=pid;chains.Clear();}}
 internal static string[] Csv(string line){var cells=new List<string>();var cell=new StringBuilder();bool quoted=false;foreach(char c in line){if(c=='"')quoted=!quoted;else if(c==','&&!quoted){cells.Add(cell.ToString());cell.Length=0;}else cell.Append(c);}if(quoted)return new string[0];cells.Add(cell.ToString());return cells.ToArray();}
 public void Line(string line){if(string.IsNullOrEmpty(line)||line.Length>8192)return;var cells=Csv(line);lock(gate){if(cells.Any(c=>c.Equals("ProcessID",StringComparison.OrdinalIgnoreCase))&&cells.Any(c=>c.Equals("msBetweenPresents",StringComparison.OrdinalIgnoreCase))){headers=cells.Select(c=>c.ToLowerInvariant()).ToArray();return;}if(headers==null||target==0||cells.Length!=headers.Length)return;int pid;double ms;int p=Array.IndexOf(headers,"processid"),m=Array.IndexOf(headers,"msbetweenpresents"),s=Array.IndexOf(headers,"swapchainaddress");if(p<0||m<0||!int.TryParse(cells[p],out pid)||pid!=target||!double.TryParse(cells[m],System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out ms)||double.IsNaN(ms)||double.IsInfinity(ms)||ms<=0||ms>10000)return;string key=s>=0?cells[s]:"main";Queue<Sample> q;if(!chains.TryGetValue(key,out q)){if(chains.Count>=32)return;chains[key]=q=new Queue<Sample>();}q.Enqueue(new Sample{Ms=ms,Time=clock.ElapsedMilliseconds});while(q.Count>2000||q.Count>0&&clock.ElapsedMilliseconds-q.Peek().Time>1200)q.Dequeue();}}
 public FrameSnapshot Snapshot(){lock(gate){long now=clock.ElapsedMilliseconds;var q=chains.Values.Where(v=>v.Count>0&&now-v.Last().Time<1500).OrderByDescending(v=>v.Count(s=>now-s.Time<1000)).FirstOrDefault();if(q==null)return new FrameSnapshot();var rows=q.Where(s=>now-s.Time<1000).ToArray();if(rows.Length<2)return new FrameSnapshot();return new FrameSnapshot{Fps=1000/rows.Average(s=>s.Ms),Times=rows.Skip(Math.Max(0,rows.Length-120)).Select(s=>s.Ms).ToArray()};}}
}
internal sealed class CaptureJob : IDisposable {
 [StructLayout(LayoutKind.Sequential)]struct Basic {public long ProcessTime,JobTime;public uint Flags;public UIntPtr Min,Max;public uint Active;public UIntPtr Affinity;public uint Priority,Scheduling;}
 [StructLayout(LayoutKind.Sequential)]struct Io {public ulong A,B,C,D,E,F;}
 [StructLayout(LayoutKind.Sequential)]struct Limits {public Basic Basic;public Io Io;public UIntPtr Process,Job,PeakProcess,PeakJob;}
 [DllImport("kernel32.dll")]static extern IntPtr CreateJobObject(IntPtr attributes,string name);
 [DllImport("kernel32.dll")]static extern bool SetInformationJobObject(IntPtr job,int type,ref Limits limits,uint size);
 [DllImport("kernel32.dll")]static extern bool AssignProcessToJobObject(IntPtr job,IntPtr process);
 [DllImport("kernel32.dll")]static extern bool CloseHandle(IntPtr handle);
 IntPtr handle;
 public CaptureJob(Process p){handle=CreateJobObject(IntPtr.Zero,null);var limits=new Limits{Basic=new Basic{Flags=0x2000}};if(handle==IntPtr.Zero||!SetInformationJobObject(handle,9,ref limits,(uint)Marshal.SizeOf(limits))||!AssignProcessToJobObject(handle,p.Handle)){Dispose();try{p.Kill();}catch{}throw new InvalidOperationException("Could not bind FPS capture to SteamCouch's lifetime.");}}
 public void Dispose(){if(handle!=IntPtr.Zero){CloseHandle(handle);handle=IntPtr.Zero;}}
}
internal sealed class PerformanceCapture : IDisposable {
 readonly FrameTracker frames;readonly object gate=new object();NamedPipeServerStream pipe;StreamWriter control;Process helper;bool disposed,paused;volatile bool requesting;int generation;public volatile string Status="FPS capture off";
 static string Exe {get{return Path.Combine(Storage.Root,@"tools\performance\PresentMon.exe");}}
 public PerformanceCapture(FrameTracker frames){this.frames=frames;}
 internal static string Arguments(string session){return "--output_stdout --no_console_stats --v1_metrics --no_track_gpu --no_track_display --no_track_input --session_name "+session;}
 public void Start(){lock(gate){if(disposed)return;bool wasPaused=paused;paused=false;if(control!=null){if(wasPaused)Command("START");return;}if(requesting||pipe!=null)return;requesting=true;}Connect(false).ContinueWith(t=>{if(t.IsFaulted)Storage.Log(t.Exception.ToString());});}
 public void Pause(){lock(gate){if(paused)return;paused=true;frames.Target(0);Command("STOP");}}
 void Command(string command){if(control==null)return;try{control.WriteLine(command);}catch(IOException){Status="FPS capture disconnected · enable capture to retry";}catch(ObjectDisposedException){}}
 public Task EnablePermission(){return EnablePermission(true);}internal Task EnablePermission(bool elevate){lock(gate){if(disposed||requesting)return Task.FromResult(0);requesting=true;}return Connect(elevate);}
 async Task Connect(bool elevate){NamedPipeServerStream server=null;int current=0;try{var security=new PipeSecurity();security.AddAccessRule(new PipeAccessRule(WindowsIdentity.GetCurrent().User,PipeAccessRights.FullControl,AccessControlType.Allow));security.AddAccessRule(new PipeAccessRule(new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid,null),PipeAccessRights.FullControl,AccessControlType.Allow));var name="SteamCouchFrames_"+Guid.NewGuid().ToString("N");lock(gate){if(disposed)return;generation++;current=generation;ClosePipe();if(helper!=null)helper.Dispose();helper=null;pipe=server=new NamedPipeServerStream(name,PipeDirection.InOut,1,PipeTransmissionMode.Byte,PipeOptions.Asynchronous,65536,65536,security);}var connect=Task.Factory.FromAsync(server.BeginWaitForConnection,server.EndWaitForConnection,null);long ticks;int pid;using(var parent=Process.GetCurrentProcess()){ticks=parent.StartTime.ToUniversalTime().Ticks;pid=parent.Id;}Status=elevate?"Waiting for Windows permission…":"Starting FPS capture…";var started=await Task.Run(()=>Process.Start(new ProcessStartInfo(typeof(Program).Assembly.Location,"--performance-capture "+pid+" "+ticks+" "+name){UseShellExecute=elevate,Verb=elevate?"runas":"",CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden}));lock(gate){if(disposed){if(started!=null)started.Dispose();return;}helper=started;}if(await Task.WhenAny(connect,Task.Delay(25000))!=connect)throw new TimeoutException("Capture did not connect. Try Enable FPS capture again.");await connect;lock(gate){if(disposed)return;control=new StreamWriter(server,new UTF8Encoding(false),1024,true){AutoFlush=true};if(paused)Command("STOP");Status="Waiting for game frames";}ObserveRead(Read(server,current));}catch(Exception e){lock(gate){if(generation==current){Status="FPS unavailable: "+e.Message;ClosePipe();}}}finally{requesting=false;}} void ObserveRead(Task read){read.ContinueWith(t=>{if(t.IsFaulted)Storage.Log(t.Exception.ToString());});}
 Task Read(NamedPipeServerStream server,int current){return Task.Run(()=>{try{using(var reader=new StreamReader(server,Encoding.UTF8,true,65536,true)){string line;while((line=reader.ReadLine())!=null){if(line.StartsWith("!"))Status=line.Substring(1);else frames.Line(line);}}}catch(IOException){}catch(ObjectDisposedException){}finally{lock(gate){if(generation==current){ClosePipe();if(!disposed)Status="FPS capture stopped · enable capture to retry";}}}});}
 void ClosePipe(){if(control!=null){try{control.Dispose();}catch(IOException){}catch(ObjectDisposedException){}control=null;}if(pipe!=null){pipe.Dispose();pipe=null;}}public void Dispose(){Process child;lock(gate){disposed=true;generation++;ClosePipe();child=helper;helper=null;}if(child!=null){try{child.WaitForExit(3500);}catch{}finally{child.Dispose();}}}
 static void TerminateSession(string session){try{using(var p=Process.Start(new ProcessStartInfo(Exe,"--session_name "+session+" --terminate_existing_session"){UseShellExecute=false,CreateNoWindow=true})){if(!p.WaitForExit(1500))p.Kill();}}catch{}}
 sealed class Run : IDisposable {
 public Process Process;CaptureJob job;volatile bool stopping;readonly string session;
 public Run(string name,Action<string> send){session=name;Process=new Process{StartInfo=new ProcessStartInfo(Exe,Arguments(session)){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true}};Process.OutputDataReceived+=(s,e)=>{if(e.Data!=null&&!stopping)send(e.Data);};Process.ErrorDataReceived+=(s,e)=>{if(e.Data!=null&&e.Data.StartsWith("error:"))send(e.Data.IndexOf("access denied",StringComparison.OrdinalIgnoreCase)>=0?"!FPS needs permission · enable capture in Settings":"!FPS unavailable: "+e.Data);};try{Process.Start();job=new CaptureJob(Process);Process.BeginOutputReadLine();Process.BeginErrorReadLine();}catch{Dispose();throw;}}
 public void Dispose(){stopping=true;if(Process!=null){try{if(!Process.HasExited)TerminateSession(session);if(!Process.WaitForExit(1000))Process.Kill();}catch{}finally{if(job!=null)job.Dispose();Process.Dispose();Process=null;}}}
 }
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetNamedPipeServerProcessId(IntPtr pipe,out uint pid);
 public static int Helper(string[] args){try{if(args.Length!=4)return 2;int pid;long ticks;if(!int.TryParse(args[1],out pid)||!long.TryParse(args[2],out ticks)||!System.Text.RegularExpressions.Regex.IsMatch(args[3],"^SteamCouchFrames_[a-f0-9]{32}$"))return 2;using(var parent=Process.GetProcessById(pid)){if(parent.StartTime.ToUniversalTime().Ticks!=ticks||parent.HasExited)return 2;using(var pipe=new NamedPipeClientStream(".",args[3],PipeDirection.InOut)){var deadline=Stopwatch.StartNew();while(!pipe.IsConnected){if(parent.HasExited||deadline.ElapsedMilliseconds>15000)return 2;try{pipe.Connect(250);}catch(TimeoutException){}}uint owner;if(!GetNamedPipeServerProcessId(pipe.SafePipeHandle.DangerousGetHandle(),out owner)||owner!=(uint)pid)return 2;using(var writer=new StreamWriter(pipe,new UTF8Encoding(false),65536,true)){writer.AutoFlush=true;object gate=new object();int requested=1;Action<string> send=line=>{try{lock(gate)writer.WriteLine(line);}catch{Interlocked.Exchange(ref requested,-1);}};Task.Run(()=>{try{using(var reader=new StreamReader(pipe,Encoding.UTF8,true,1024,true)){string line;while((line=reader.ReadLine())!=null){if(line=="START")Interlocked.Exchange(ref requested,1);else if(line=="STOP")Interlocked.Exchange(ref requested,0);}}}catch{}finally{Interlocked.Exchange(ref requested,-1);}});Run run=null;bool active=false;try{while(Volatile.Read(ref requested)>=0&&!parent.HasExited){bool wanted=Volatile.Read(ref requested)==1;if(wanted!=active){if(run!=null){run.Dispose();run=null;}active=wanted;if(wanted)run=new Run("SteamCouch_"+Guid.NewGuid().ToString("N"),send);}if(run!=null&&run.Process.HasExited){run.Dispose();run=null;}Thread.Sleep(100);}}finally{if(run!=null)run.Dispose();}}}}return 0;}catch{return 1;}}
}
}