using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace TVLounge {
internal sealed class MenuNavigation {
 ushort previous;long next;bool armed;readonly System.Diagnostics.Stopwatch watch=System.Diagnostics.Stopwatch.StartNew();
 public void Reset(){armed=false;previous=0;}
 public ushort Sample(ushort buttons){buttons&=0xf00f;if(!armed){if(buttons==0)armed=true;return 0;}long now=watch.ElapsedMilliseconds;ushort pressed=(ushort)(buttons&~previous);if((buttons&15)!=0&&now>=next){pressed|=(ushort)(buttons&15);next=now+180;}else if((pressed&15)!=0)next=now+400;previous=buttons;return pressed;}
}
internal sealed class QuickMenuWindow : Form {
 readonly IDevices devices;readonly Func<Task> desktop;readonly bool allowSleep;readonly Func<Task> sleep;bool sleepPrompt,profileTrial;readonly bool preview;readonly string monitor;ScreenTarget target;List<VideoMode> modes=new List<VideoMode>();List<Row> outputs=new List<Row>();List<string> choices=new List<string>();string currentMode="",outputName="Current playback output",message="";bool hdrOn,hdrSupported,muted,loading,restoring;int volume,index,page,choice;VideoTrial trial;DateTime lastRead;readonly System.Windows.Forms.Timer timer=new System.Windows.Forms.Timer{Interval=80};readonly MenuNavigation navigation=new MenuNavigation();bool ticking;Image logo;IntPtr previousWindow;
 [DllImport("user32.dll")]static extern IntPtr GetForegroundWindow();[DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr window);[DllImport("user32.dll")]static extern bool IsWindow(IntPtr window);
 public bool CanClose {get{return !loading;}}
 public QuickMenuWindow(IDevices devices,string monitor,Func<Task> desktop,bool preview,bool allowSleep=false,Func<Task> sleep=null){this.allowSleep=allowSleep;this.sleep=sleep;this.devices=devices;this.monitor=monitor;this.desktop=desktop;this.preview=preview;previousWindow=GetForegroundWindow();Text="SteamCouch — Quick menu";FormBorderStyle=FormBorderStyle.None;TopMost=true;ShowInTaskbar=false;StartPosition=FormStartPosition.Manual;AutoScaleMode=AutoScaleMode.None;DoubleBuffered=true;BackColor=Theme.Background;ForeColor=Theme.Text;KeyPreview=true;AccessibleName="SteamCouch TV quick menu";AccessibleDescription="Use arrows or D-pad to navigate, A or Enter to select, B or Escape to go back.";
 string path=Path.Combine(Storage.Root,"assets","steamcouch.png");if(File.Exists(path)){using(var image=Image.FromFile(path))logo=new Bitmap(image);}PlaceOnTv();
 Shown+=async delegate{await RefreshValues();Activate();};timer.Tick+=async delegate{if(ticking)return;ticking=true;try{if(trial!=null&&trial.Finished){message=trial.Error??"Previous display settings restored.";if(profileTrial){GameProfiles.ClearRejected();profileTrial=false;}trial=null;await RefreshValues();}if(trial!=null)Invalidate();if(!preview){ushort keys=0;for(uint i=0;i<4;i++)keys|=ControllerInput.NavigationButtons(i);ushort press=navigation.Sample(keys);if(!loading){if((press&0x2000)!=0)Back();else if((press&0x1000)!=0)await SelectAction();else if((press&0x4000)!=0&&page==0&&index==0)await ChangeMute();else if((press&1)!=0)Navigate(-2);else if((press&2)!=0)Navigate(2);else if((press&4)!=0)await Horizontal(-1);else if((press&8)!=0)await Horizontal(1);}}if(!loading&&trial==null&&DateTime.UtcNow-lastRead>TimeSpan.FromSeconds(3))await RefreshValues();}catch(Exception error){message=error.Message;Storage.Log(error.ToString());Invalidate();}finally{ticking=false;}};
 timer.Start();FormClosing+=delegate(object sender,FormClosingEventArgs e){if(loading){e.Cancel=true;return;}if(trial!=null)try{trial.Revert();trial=null;if(profileTrial){GameProfiles.ClearRejected();profileTrial=false;}}catch(Exception error){message="Restore failed: "+error.Message;e.Cancel=true;Invalidate();}};
 FormClosed+=delegate{timer.Stop();timer.Dispose();if(logo!=null)logo.Dispose();if(!restoring&&IsWindow(previousWindow))SetForegroundWindow(previousWindow);};
 }
 protected override CreateParams CreateParams {get{var p=base.CreateParams;p.ClassStyle|=0x20000;return p;}}
 void PlaceOnTv(){var screen=Screen.AllScreens.FirstOrDefault(s=>string.Equals(s.DeviceName,monitor,StringComparison.OrdinalIgnoreCase));if(screen==null){if(!preview)throw new InvalidOperationException("The TV is no longer connected. Restore desktop and reconnect it.");screen=Screen.PrimaryScreen;}int h=screen.Bounds.Height,w=screen.Bounds.Width;float size=Math.Min(w/860f,h/800f);size=Math.Max(.65f,Math.Min(2.5f,size));Size=new Size((int)(720*size),(int)(660*size));Location=new Point(screen.Bounds.Left+(w-Width)/2,screen.Bounds.Top+(h-Height)/2);}
 float UiScale {get{return ClientSize.Width/720f;}}
 Rectangle Rect(int x,int y,int w,int h){float s=UiScale;return new Rectangle((int)(x*s),(int)(y*s),(int)(w*s),(int)(h*s));}
 void TextAt(Graphics g,string text,int x,int y,int w,int h,int size,bool bold,Color color){using(var font=new Font("Segoe UI",size*UiScale, bold?FontStyle.Bold:FontStyle.Regular,GraphicsUnit.Pixel))TextRenderer.DrawText(g,text,font,Rect(x,y,w,h),color,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
 void Box(Graphics g,Rectangle rect,bool selected){using(var shape=Theme.Round(rect,12*UiScale)){using(var b=new SolidBrush(selected?Color.FromArgb(38,66,83):Theme.Surface))g.FillPath(b,shape);using(var pen=new Pen(selected?Theme.Accent:Theme.Border,selected?2*UiScale:UiScale))g.DrawPath(pen,shape);}}
 int TileStep {get{return allowSleep?98:126;}}int TileHeight {get{return allowSleep?86:112;}}int TileCount {get{return allowSleep?7:6;}}
 string[] titles={"Volume","Audio output","HDR","Resolution & refresh","Windows VRR assistance","Return to desktop","Sleep PC"};string[] glyphs={"\uE767","\uE7F5","\uE793","\uE7F4","\uE9D9","\uE80F","\uE708"};
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;using(var pen=new Pen(Theme.Border,2*UiScale))g.DrawRectangle(pen,new Rectangle(1,1,Width-3,Height-3));if(logo!=null)g.DrawImage(logo,Rect(26,23,46,46));TextAt(g,"SteamCouch",86,20,500,32,25,true,Theme.Text);TextAt(g,page==0?"YOUR COUCH CONTROLS":page==1?"CHOOSE AUDIO OUTPUT":"CHOOSE RESOLUTION & REFRESH RATE",86,56,580,24,11,true,Theme.Accent);
 if(sleepPrompt){Box(g,Rect(26,113,668,347),true);TextAt(g,"Put your PC to sleep?",52,140,600,60,27,true,Theme.Text);TextAt(g,"Your desktop is restored first. Games are not force-closed.",52,220,600,58,17,false,Theme.Muted);TextAt(g,"A / Enter   Restore desktop and sleep",52,300,600,40,22,true,Theme.Accent);TextAt(g,"B / Esc       Cancel",52,355,600,40,20,false,Theme.Text);}
 else if(trial!=null){int remaining=Math.Max(0,(int)Math.Ceiling((trial.Deadline-DateTime.UtcNow).TotalSeconds));Box(g,Rect(26,113,668,347),true);TextAt(g,"Keep these display settings?",52,140,600,60,27,true,Theme.Text);TextAt(g,trial.Error??("Automatically reverting in "+remaining+" seconds"),52,220,600,44,20,false,Theme.Muted);TextAt(g,"A / Enter   Keep settings",52,300,600,40,22,true,Theme.Accent);TextAt(g,"B / Esc       Revert now",52,355,600,40,20,false,Theme.Text);}
 else if(page==0){string[] values={muted?"Muted · "+volume+"%":volume+"%",outputName,hdrSupported?(hdrOn?"On":"Off"):"Unavailable on this connection",currentMode,preview?"Off":WindowsVrr.Enabled?"On · restart game to apply":"Off · restart game to apply","Restore your normal setup","Confirm before sleeping"};for(int i=0;i<TileCount;i++){int x=26+(i%2)*344,y=108+(i/2)*TileStep;int tileWidth=i==6?668:324;Box(g,Rect(x,y,tileWidth,TileHeight),i==index);using(var f=new Font("Segoe MDL2 Assets",23*UiScale,FontStyle.Regular,GraphicsUnit.Pixel))TextRenderer.DrawText(g,glyphs[i],f,Rect(x+18,y+18,32,34),Theme.Accent,TextFormatFlags.VerticalCenter);TextAt(g,titles[i],x+61,y+15,249,31,17,true,Theme.Text);TextAt(g,values[i],x+18,y+(allowSleep?48:57),tileWidth-36,allowSleep?32:37,i==0?25:15,i==0,Theme.Muted);}TextAt(g,index==0?"Left / Right changes volume · X mutes":index==4?"Windows-wide option. Enable FreeSync/G-SYNC on your TV and GPU too.":"A / Enter to select",28,allowSleep?505:490,664,40,14,false,Theme.Muted);}
 else {int start=Math.Max(0,Math.Min(choice-3,choices.Count-6));for(int row=0;row<Math.Min(6,choices.Count);row++){int item=start+row;Box(g,Rect(26,108+row*64,668,55),item==choice);TextAt(g,choices[item],46,114+row*64,625,42,19,item==choice,Theme.Text);}TextAt(g,"A / Enter to apply · B / Esc to go back",28,505,664,28,14,false,Theme.Muted);}
 TextAt(g,loading?"Working…":message,28,545,664,53,14,false,Theme.Accent);TextAt(g,"D-pad  Navigate       A  Select       B  Resume game",28,613,664,28,15,true,Theme.Text);
 }
 async Task RefreshValues(){if(loading)return;loading=true;try{if(preview){volume=65;currentMode="3840 × 2160 · 120 Hz";outputName="Living room TV";hdrSupported=true;hdrOn=true;muted=false;modes=new List<VideoMode>{new VideoMode{Width=3840,Height=2160,Frequency=120},new VideoMode{Width=3840,Height=2160,Frequency=60},new VideoMode{Width=2560,Height=1440,Frequency=120},new VideoMode{Width=1920,Height=1080,Frequency=120}};}else{var result=await Task.Run(()=>{var t=VideoNative.Target(monitor);var h=VideoNative.Hdr(t);var mode=VideoNative.Current(monitor);var displayModes=VideoNative.Modes(monitor);var audio=devices.Audio().Where(r=>r.Get("Device State")=="Active").ToList();int percent;bool mute;using(var v=new SessionVolume()){percent=v.Percent;mute=v.Muted;}return new {Target=t,Hdr=h,Mode=mode,Modes=displayModes,Audio=audio,Percent=percent,Mute=mute};});target=result.Target;hdrSupported=result.Hdr.Supported;hdrOn=result.Hdr.Enabled;currentMode=result.Mode.ToString();modes=result.Modes;outputs=result.Audio;volume=result.Percent;muted=result.Mute;var output=outputs.FirstOrDefault(r=>r.Get("Default Multimedia")=="Render");outputName=output==null?"Current playback output":output.Get("Name");}lastRead=DateTime.UtcNow;PlaceOnTv();}catch(Exception e){message=e.Message;Storage.Log(e.ToString());}finally{loading=false;Invalidate();}}
 async Task Action(Func<Task> action){if(loading)return;loading=true;Invalidate();try{if(preview){message="Preview only — no settings changed.";return;}await action();message="Updated for this TV session.";}catch(Exception e){message=e.Message;Storage.Log(e.ToString());}finally{loading=false;navigation.Reset();}await RefreshValues();}
 async Task ChangeMute(){await Action(()=>Task.Run(()=>{using(var v=new SessionVolume())v.Muted=!v.Muted;}));}
 async Task Horizontal(int step){if(trial!=null||sleepPrompt||loading)return;if(page!=0){Navigate(step);return;}if(index==0)await Action(()=>Task.Run(()=>{using(var v=new SessionVolume())v.Percent=v.Percent+5*step;}));else {index=(index+step+TileCount)%TileCount;Invalidate();}}
 void Navigate(int step){if(loading||trial!=null||sleepPrompt)return;if(page==0)index=Math.Max(0,Math.Min(TileCount-1,index+step));else choice=Math.Max(0,Math.Min(choices.Count-1,choice+Math.Sign(step)));Invalidate();}
 async Task SelectAction(){try{await SelectCore();}catch(Exception error){message=error.Message;Storage.Log(error.ToString());Invalidate();}}
 async Task SelectCore(){if(loading)return;if(sleepPrompt){sleepPrompt=false;if(preview){message="Preview only — your PC will not sleep.";Invalidate();return;}if(!allowSleep||sleep==null)return;restoring=true;Close();await sleep();return;}if(trial!=null){bool kept=trial.Confirm();if(profileTrial){if(!kept)GameProfiles.ClearRejected();profileTrial=false;}trial=null;message=kept?"Display settings kept for this TV session.":"Confirmation expired. Previous settings restored.";await RefreshValues();return;}if(page==1){if(choice<0||choice>=outputs.Count)return;string id=outputs[choice].Get("Item ID");await Action(()=>Task.Run(()=>{for(int role=0;role<3;role++)devices.SetAudio(id,role);if(!Engine.Defaults(devices.Audio()).All(v=>v==id))throw new InvalidOperationException("Windows did not switch the audio output.");}));page=0;index=1;Invalidate();return;}if(page==2){if(choice<0||choice>=modes.Count)return;var mode=modes[choice];await BeginTrial(mode,null);return;}if(index==0){await ChangeMute();return;}if(index==1){page=1;choices=outputs.Select(r=>r.Get("Name")+" · "+r.Get("Device Name")).ToList();choice=Math.Max(0,outputs.FindIndex(r=>r.Get("Default Multimedia")=="Render"));}else if(index==2){if(!hdrSupported){message="HDR requires a supported TV, GPU and connection.";}else await BeginTrial(new VideoMode(),!hdrOn);}else if(index==3){page=2;choices=modes.Select(m=>m.ToString()).ToList();choice=Math.Max(0,modes.FindIndex(m=>m.ToString()==currentMode));}else if(index==4){await Action(()=>Task.Run(()=>VideoSession.SetVrr(!WindowsVrr.Enabled)));message="Windows VRR preference saved. Restart the game to apply it.";}else if(index==5){if(preview){message="Preview only — your desktop is unchanged.";}else{restoring=true;Close();await desktop();}}else if(index==6&&allowSleep){RequestSleep();}Invalidate();}
 async Task BeginTrial(VideoMode mode,bool? hdr){if(preview){message="Preview only — no display changes.";Invalidate();return;}loading=true;try{trial=await Task.Run(()=>new VideoTrial(target,mode,hdr));page=0;navigation.Reset();message="Confirm the change, or it will revert automatically.";PlaceOnTv();}catch(Exception e){message=e.Message;Storage.Log(e.ToString());}finally{loading=false;Invalidate();}}
 void Back(){if(loading)return;if(sleepPrompt){sleepPrompt=false;navigation.Reset();Invalidate();return;}if(trial!=null){try{trial.Revert();trial=null;if(profileTrial){GameProfiles.ClearRejected();profileTrial=false;}message="Previous settings restored.";}catch(Exception e){message=e.Message;}}else if(page!=0)page=0;else Close();navigation.Reset();Invalidate();}
 protected override bool ProcessCmdKey(ref Message msg,Keys key){switch(key&Keys.KeyCode){case Keys.Escape:Back();return true;case Keys.Enter:SelectAction().ContinueWith(t=>{if(t.IsFaulted)Storage.Log(t.Exception.ToString());});return true;case Keys.Up:Navigate(-2);return true;case Keys.Down:Navigate(2);return true;case Keys.Left:Horizontal(-1).ContinueWith(t=>{if(t.IsFaulted)Storage.Log(t.Exception.ToString());});return true;case Keys.Right:Horizontal(1).ContinueWith(t=>{if(t.IsFaulted)Storage.Log(t.Exception.ToString());});return true;}return base.ProcessCmdKey(ref msg,key);}
 protected override async void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(loading)return;float x=e.X/UiScale,y=e.Y/UiScale;if(trial!=null||sleepPrompt){if(y>=290&&y<=345)await SelectAction();else if(y>=345&&y<=410)Back();return;}if(page==0){for(int i=0;i<TileCount;i++)if(Rect(26+(i%2)*344,108+(i/2)*TileStep,i==6?668:324,TileHeight).Contains(e.Location)){index=i;await SelectAction();return;}}else{int start=Math.Max(0,Math.Min(choice-3,choices.Count-6));for(int row=0;row<Math.Min(6,choices.Count);row++)if(Rect(26,108+row*64,668,55).Contains(e.Location)){choice=start+row;await SelectAction();return;}}if(y>=607)Back();Invalidate();}
 protected override async void OnMouseWheel(MouseEventArgs e){base.OnMouseWheel(e);if(page==0&&index==0)await Horizontal(Math.Sign(e.Delta));else Navigate(-Math.Sign(e.Delta));}
  public void RequestSleep(){if(!allowSleep||loading||trial!=null)return;sleepPrompt=true;navigation.Reset();Invalidate();}
 public async Task ApplyProfile(GameProfile profile){if(loading||trial!=null)return;loading=true;profileTrial=true;try{trial=await GameProfiles.Begin(monitor,profile);message="Game profile: "+profile.Name;page=0;navigation.Reset();PlaceOnTv();}catch(Exception error){GameProfiles.ClearRejected();profileTrial=false;message=error.Message;Storage.Log(error.ToString());}finally{loading=false;Invalidate();}}
 internal async Task WriteOptionalPreviews(){await RefreshValues();Size=new Size(900,825);using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,ClientRectangle);b.Save(Storage.PathOf("quick-menu-sleep-enabled.png"));}RequestSleep();using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,ClientRectangle);b.Save(Storage.PathOf("sleep-confirmation.png"));}sleepPrompt=false;trial=new VideoTrial(new VideoPending{Target=new ScreenTarget{Path="preview",Device="preview"}},()=>{},p=>{},20000);using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,ClientRectangle);b.Save(Storage.PathOf("game-profile-confirmation.png"));}trial.Revert();trial=null;}
 internal async Task WritePreviews(){await RefreshValues();foreach(int width in new[]{720,1080,1440}){Size=new Size(width,width*660/720);using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,ClientRectangle);b.Save(Storage.PathOf("quick-menu-"+width+".png"));}}page=2;choices=modes.Select(m=>m.ToString()).ToList();choice=0;using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,ClientRectangle);b.Save(Storage.PathOf("quick-menu-modes.png"));}}
}
}
